table=[
"48 48 194 2 ",
"   c None",
".  c #AA6309",
"X  c #AD670A",
"o  c #AE690B",
"O  c #BD6A00",
"+  c #B26E0A",
"@  c #B5710B",
"#  c #B7750B",
"$  c #B9780B",
"%  c #BC7B0C",
"&  c #BE7E0C",
"*  c #B7701E",
"=  c #825A36",
"-  c #835B36",
";  c #855B36",
":  c #875C36",
">  c #8F5F34",
",  c #936033",
"<  c #926034",
"1  c #946134",
"2  c #986232",
"3  c #C06E00",
"4  c #C37201",
"5  c #C67601",
"6  c #C77802",
"7  c #C97A01",
"8  c #CC7E01",
"9  c #CC7E02",
"0  c #C67A0A",
"q  c #BD821B",
"w  c #CF8101",
"e  c #C0810C",
"r  c #C2840C",
"t  c #C5870D",
"y  c #C78A0D",
"u  c #C98D0D",
"i  c #D18502",
"p  c #D48902",
"a  c #D78C02",
"s  c #D38B09",
"d  c #CB900E",
"f  c #CE930E",
"g  c #DA9003",
"h  c #DA9103",
"j  c #DC9403",
"k  c #DF9703",
"l  c #D0970E",
"z  c #D2980D",
"x  c #D29A0F",
"c  c #D59C0E",
"v  c #D79E0E",
"b  c #D79F0F",
"n  c #D28F14",
"m  c #D29E10",
"M  c #D39E10",
"N  c #D29F11",
"B  c #D29E12",
"V  c #D29F12",
"C  c #D9991D",
"Z  c #E38309",
"A  c #EA860A",
"S  c #FC8E01",
"D  c #FE8E00",
"F  c #FF8F00",
"G  c #E29B04",
"H  c #E59F04",
"J  c #E59F05",
"K  c #E19E0D",
"L  c #FE9100",
"P  c #D9A10E",
"I  c #DAA40F",
"U  c #D9A712",
"Y  c #DDA710",
"T  c #DFA014",
"R  c #DFA51F",
"E  c #E7A204",
"W  c #EAA605",
"Q  c #EDAA05",
"!  c #E4A008",
"~  c #E1AC0F",
"^  c #ECAE08",
"/  c #FBA203",
"(  c #F0AD05",
")  c #F0AD06",
"_  c #EFB007",
"`  c #F2B006",
"'  c #F3B206",
"]  c #F4B305",
"[  c #F4B306",
"{  c #F6B505",
"}  c #F4B406",
"|  c #F5B406",
" . c #F6B606",
".. c #F8B906",
"X. c #FBBA06",
"o. c #FABB06",
"O. c #FBBB07",
"+. c #EBAF12",
"@. c #EEB71B",
"#. c #E9B31E",
"$. c #CC9827",
"%. c #C3A12C",
"&. c #D5A620",
"*. c #D6A932",
"=. c #D6AD37",
"-. c #D8AA32",
";. c #DBAC32",
":. c #DBAD32",
">. c #DEAE32",
",. c #DBAE34",
"<. c #D7AF39",
"1. c #D7B63F",
"2. c #D8B33B",
"3. c #E2AC29",
"4. c #ECB72E",
"5. c #EAB92B",
"6. c #E0B234",
"7. c #E6B936",
"8. c #E2BC3D",
"9. c #F2C72E",
"0. c #EDC135",
"q. c #EDC83F",
"w. c #FBC532",
"e. c #FCC632",
"r. c #F2CA36",
"t. c #FBC935",
"y. c #FBCB37",
"u. c #FCC935",
"i. c #FCCB37",
"p. c #F1C338",
"a. c #F3CA3C",
"s. c #FACE3A",
"d. c #FCCE3A",
"f. c #FCD03C",
"g. c #FCD13D",
"h. c #FCD33F",
"j. c #FDD33F",
"k. c #D7B842",
"l. c #D7BC46",
"z. c #D7BE47",
"x. c #D3BD48",
"c. c #DEC044",
"v. c #DAC149",
"b. c #D8C24B",
"n. c #D8C44C",
"m. c #D9C74F",
"M. c #D9C84F",
"N. c #D7C952",
"B. c #D8C850",
"V. c #D9CA51",
"C. c #DACB52",
"Z. c #DBCD53",
"A. c #DDCD51",
"S. c #DECF53",
"D. c #DED053",
"F. c #E9CB46",
"G. c #E5CC4B",
"H. c #E1CD4E",
"J. c #F5D442",
"K. c #F8D342",
"L. c #FDD642",
"P. c #FCD844",
"I. c #FDD844",
"U. c #FDDB47",
"Y. c #F4D648",
"T. c #F1D84D",
"R. c #FBDB48",
"E. c #FCDD49",
"W. c #FDDD49",
"Q. c #FDDF4A",
"!. c #E4D554",
"~. c #E8D752",
"^. c #EDD951",
"/. c #FBE24E",
"(. c #FDE14C",
"). c #FEE14C",
"_. c #FEE34E",
"`. c #FDE44F",
"'. c #FEE44F",
"]. c #F1E055",
"[. c #F4E254",
"{. c #F8E453",
"}. c #FEE651",
"|. c #FFE852",
" X c #FEE953",
".X c #FFE953",
"XX c #FEEA54",
"oX c #FFEA54",
"OX c #FEEB55",
"+X c #FFEB55",
"@X c #FEEC56",
"#X c #FFEC56",
"$X c #FEED57",
"%X c #FFED57",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"    U ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ K Z Z Z Z Z Z Z Z * : : : : : : ; =                                   ",
"    Y ......................L F F F F F F F A , 1 , , 1 , > =                                   ",
"    Y ....................../ F F F F F F F F 2 1 , , 1 , < =                                   ",
"    I  . . . . . . . . . . . . . . . . . . . . . . . . . . .P B B B B B B B B B B               ",
"    P ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ` _ _ _ _ _ _ _ _ ^ B               ",
"    c ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` ` P               ",
"    c ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) c               ",
"    x Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q c               ",
"    l W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W W x               ",
"    f E E E E E E +.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.@.&.%.            ",
"    d H H H H H 9.$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X].D.A.A.A.Z.N.  ",
"    u G G G G ! OX$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X!.    ",
"    y j j j j #.$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$X$XOXV.    ",
"    t j j j j r.OX$XOX$XOXOXOX$XOXOX$XOXOX$XOXOX$XOXOX$XOXOX$XOX$XOXOX$XOXOX$XOXOX$XOXOX[.V.    ",
"    r g g g g /.OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOX~.V.    ",
"    e a a a T OXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXA.      ",
"    & p p p 5. X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X{.M.      ",
"    % i i i J. X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X X^.m.      ",
"    $ w w s }.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.}.H.        ",
"    # 8 8 R `.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`.`./.m.        ",
"    @ 7 7 0._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.T.v.        ",
"    + 5 6 R._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.G.x.        ",
"    o 4 n E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.v.          ",
"    X 3 3.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.E.Y.z.          ",
"    . O a.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.F.z.          ",
"    . 0 U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.c.            ",
"    . C L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.L.K.k.            ",
"    . 4.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.q.1.            ",
"    o s.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.d.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.8.              ",
"    q d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.d.s.2.              ",
"    $.u.y.y.u.y.y.u.y.u.y.y.y.u.y.y.u.y.y.u.y.y.u.y.y.u.y.y.u.y.u.y.y.u.y.y.u.p.<.              ",
"    :.u.y.y.u.y.y.u.y.u.y.y.y.u.y.y.u.y.y.u.y.y.u.y.y.u.y.y.u.y.u.y.y.u.y.y.u.7.=.              ",
"    6.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.e.w.,.                ",
"    -.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.:.*.                ",
"                                                                                                ",
"                                                                                                "
]