table=[
"48 48 211 2 ",
"   c None",
".  c #24282D",
"X  c #454C56",
"o  c #464D57",
"O  c #505761",
"+  c #517195",
"@  c #587699",
"#  c #667E9D",
"$  c #627FA0",
"%  c #6E86A0",
"&  c #6A84A4",
"*  c #7086A1",
"=  c #7288A2",
"-  c #718BA9",
";  c #738DAB",
":  c #7F92AB",
">  c #7991AE",
",  c #7B92AF",
"<  c #7C94B0",
"1  c #7E96B2",
"2  c #7F96B3",
"3  c #7F98B4",
"4  c #7AB9D6",
"5  c #7BBAD7",
"6  c #7CBCD9",
"7  c #7EBDDA",
"8  c #8197AF",
"9  c #8698B0",
"0  c #8198B4",
"q  c #8199B4",
"w  c #839BB6",
"e  c #849AB6",
"r  c #899FBA",
"t  c #8BA0BB",
"y  c #8DA2BD",
"u  c #90A4BE",
"i  c #95A9C3",
"p  c #97ACC4",
"a  c #9AABC1",
"s  c #98ACC5",
"d  c #9BADC4",
"f  c #9BAEC7",
"g  c #9BAEC8",
"h  c #9DB0C8",
"j  c #9EB1CA",
"k  c #83BDD9",
"l  c #80BEDB",
"z  c #A0B3C9",
"x  c #A1B4CC",
"c  c #A4B7CE",
"v  c #A4B7CF",
"b  c #A8BAD2",
"n  c #AFBED0",
"m  c #ADBED4",
"M  c #85C0DB",
"N  c #82C0DD",
"B  c #83C1DE",
"V  c #84C2DE",
"C  c #85C3DF",
"Z  c #89C1DC",
"A  c #8AC4DF",
"S  c #B4C3D4",
"D  c #B6C5D6",
"F  c #BFCBD7",
"G  c #B9C7D8",
"H  c #B9C8DA",
"J  c #BDCADA",
"K  c #BDCBDC",
"L  c #BECCDD",
"P  c #BECDDE",
"I  c #BFCDDE",
"U  c #BFCEDE",
"Y  c #86C4E0",
"T  c #87C5E1",
"R  c #88C6E3",
"E  c #8DC7E1",
"W  c #8AC8E3",
"Q  c #8BC8E3",
"!  c #8BC9E4",
"~  c #8CCBE5",
"^  c #8FCAE4",
"/  c #8ECCE7",
"(  c #8FCCE8",
")  c #92CCE5",
"_  c #94CEE7",
"`  c #B2DCED",
"'  c #B9D9E8",
"]  c #C1CCD9",
"[  c #C2CEDD",
"{  c #C0CEDF",
"}  c #D3D4D6",
"|  c #D4D6D8",
" . c #D6D8D9",
".. c #D8D9DA",
"X. c #D8DADC",
"o. c #DADADC",
"O. c #DADBDC",
"+. c #DADBDD",
"@. c #DBDCDD",
"#. c #DCDDDE",
"$. c #DCDDDF",
"%. c #DEDEDF",
"&. c #DEDFDF",
"*. c #C0CFE0",
"=. c #C1CFE0",
"-. c #C2D0E1",
";. c #C3D1E1",
":. c #C6D2E0",
">. c #C5D3E2",
",. c #C7D4E3",
"<. c #C9D4E2",
"1. c #CCD7E3",
"2. c #C9D6E4",
"3. c #CAD6E4",
"4. c #CDD7E4",
"5. c #CCD7E6",
"6. c #CED9E7",
"7. c #C1DEEB",
"8. c #CFDAE8",
"9. c #D2DBE6",
"0. c #DDDEE0",
"q. c #DEDFE0",
"w. c #D0DAE8",
"e. c #D1DCE9",
"r. c #D1DCEA",
"t. c #D1DDEA",
"y. c #D3DEEB",
"u. c #C5E0ED",
"i. c #C7E2EF",
"p. c #DFE0E0",
"a. c #DFE0E1",
"s. c #DFE1E2",
"d. c #D5E0EC",
"f. c #D5E0ED",
"g. c #D6E0ED",
"h. c #D7E1ED",
"j. c #D8E0E9",
"k. c #D9E2EE",
"l. c #DAE3EF",
"z. c #DAE6ED",
"x. c #DBE5EF",
"c. c #C8E4F0",
"v. c #CAE5F1",
"b. c #CBE6F2",
"n. c #D3E7F1",
"m. c #DCE6F0",
"M. c #DDE6F0",
"N. c #DFE8F1",
"B. c #DFEFF6",
"V. c #E0E1E2",
"C. c #E0E1E3",
"Z. c #E1E2E2",
"A. c #E1E2E3",
"S. c #E1E2E4",
"D. c #E2E3E4",
"F. c #E3E4E5",
"G. c #E3E5E6",
"H. c #E4E4E4",
"J. c #E4E5E6",
"K. c #E5E6E7",
"L. c #E6E6E7",
"P. c #E6E7E8",
"I. c #E7E8E9",
"U. c #E8E8E9",
"Y. c #E8E9EA",
"T. c #EAEBEB",
"R. c #E9EBEC",
"E. c #EBECEE",
"W. c #ECEDEE",
"Q. c #E1E9F0",
"!. c #E0E8F2",
"~. c #E1E9F2",
"^. c #E2EAF4",
"/. c #E3EBF4",
"(. c #E4EBF5",
"). c #E5ECF5",
"_. c #E5ECF6",
"`. c #E6EDF6",
"'. c #E5EFF6",
"]. c #E6EEF6",
"[. c #E7EEF7",
"{. c #ECEEF0",
"}. c #EDEFF0",
"|. c #ECEEF1",
" X c #ECEFF1",
".X c #E5F0F6",
"XX c #EFF0F1",
"oX c #EDF0F2",
"OX c #EFF0F2",
"+X c #EFF1F2",
"@X c #EFF1F3",
"#X c #EAF0F8",
"$X c #EBF1F8",
"%X c #EDF3F8",
"&X c #F0F1F2",
"*X c #F1F2F4",
"=X c #F1F3F4",
"-X c #F2F3F5",
";X c #F3F4F5",
":X c #F3F5F6",
">X c #F5F6F7",
",X c #F7F7F8",
"<X c #F8F9F9",
"1X c #F9F9FA",
"2X c #FAFAFB",
"3X c #FAFBFB",
"4X c #FBFBFB",
"5X c #FBFCFC",
"6X c gray99",
"7X c #FDFDFD",
"8X c #FDFDFE",
"                                                                                                ",
"                                                                                                ",
"      @ 1 w w w w w w w w w w w w w ;                                                           ",
"      m b b b b b b b b b b b b b b b p                                                         ",
"    f v v v v v v v v v v v v v v v v v 3                                                       ",
"    j x x x x x x x x x x x x x x x x x v $                                                     ",
"    j j j j j j j j j j j j j j j j j j j z +                                                   ",
"    f g f f g f f g f g f f f g f f g f f g z w w w w w w w w w w w w w w w w w w w w 1 @       ",
"    f i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i i f       ",
"    u y t t r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r r t t y e     ",
"    e 1 > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > 1 -     ",
"    8 # * = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = * # &     ",
"    8 j.#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#X#Xj.%     ",
"    F _._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._._.]     ",
"    9.(.(.(.(.(.(.(.(.(.(.(.(.(.(._.(._._._._._._._._._._._._._._._._._._._._._._._._._._.9.    ",
"    9.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.^.(.^.(.(.(.(.(.(.(.(.(.(.(.(.(.9.    ",
"    5.~.~.~.~.~.~.~.~.~.~.~.~.~.~.~.^.%X_._._._..X_._..X_._..X_..X_._..X_._..X_._..X_.%X^.9.    ",
"    5.N.N.N.N.N.N.N.N.N.N.N.N.N.N.N.~.' 4 4 4 4 6 6 6 k k N N V T T T R W ! ^ ^ / / ( u.^.1.    ",
"    1.M.x.x.M.x.x.M.x.M.x.M.M.M.M.M.~.' 4 4 7.u.u.u.u.u.u.u.u.u.v.v.v.v.v.v.v.v.v.v.v.B.#X~.x.  ",
"    <.x.l.l.x.l.l.x.l.x.l.l.x.x.x.x.M.7.Z Z 7.4 4 4 4 6 6 6 k k N N V V T T R W W ! ^ ^ / / `   ",
"    <.l.l.l.l.l.l.l.l.l.l.l.l.l.l.l.M.6X6X6Xn.4 4 4 4 6 6 6 6 k N N V V T T R W W ! ^ ^ / / `   ",
"    >.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.l.6X6X4Xn.k k k k M M M V Z A A A E E E ^ ^ ^ ) ) _ _ _ `   ",
"    >.h.h.h.h.h.h.h.h.h.h.h.h.h.h.h.l.6X6XJ.4X6X6X6X6X6X6X5X6X4X5X4X4X5X4X4X4X4X4X4X4X4X4X4X,X  ",
"    [ y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.h.6X6XP.4X6X4X6X4X4X5X4X5X4X4X4X4X4X4X;X4X4X4X4X,X>X,X4X4X  ",
"    [ y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.y.5X4XD.,X5XT.Z.J.q.J.D.Z.J.#.J.Z.#.J.p.q.D.#.O.Z.T.F.,X,X  ",
"    [ 8.8.8.8.8.w.w.w.w.w.w.w.w.w.w.y.4X4XXX4X6XT.p.T.J.@.J.J.p.#.Z.Z.Z.Z.#.F.p.@.#.P.&X}.;X>X  ",
"    J 6.6.6.6.6.6.6.6.6.6.6.6.6.6.6.w.5X5XW.4X6XE.Z.p.T...J.Z.#.J.#.J.Z.D.Z.Z.#.@.Z.Z.p.O.&X,X  ",
"    J 5.5.5.5.5.5.5.5.5.5.5.5.5.5.5.6.4X4XJ.,X4XJ.#.D.D.Z.p.F.@.D.O.#.J.Z.#...p...@.Z.p.@.&X>X  ",
"    G 3.3.3.3.3.3.3.3.3.3.3.3.3.3.3.5.4X4XZ.,X4XT.p.Z.D.p.p.F.#.p.Z.q.J.p.#.F.D.#.@.Z...Z.;X>X  ",
"    G ,.,.,.,.,.,.,.,.,.,.,.,.,.,.,.5.4X4XF.,X4XT.J.q.D.F.J.Z.O.#.p.q.q.F.D. .J.q...q.@.q.R.>X  ",
"    D >.>.>.>.>.>.>.>.>.>.>.>.>.>.>.3.4X4XT.>X4XT.J.T.Z.D.J.Z.Z.J.D.p.P.p.J.p.J.D.Z.F.#.@.T.;X  ",
"    D ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.,.4X4XJ.,X4XE.#.D.Z.q.F.D.D.Z.p.W.,X>X>X;X>X>X>X;X;X;X;X;X  ",
"    D ;.;.;.;.;.;.;.;.;.;.;.;.;.;.;.>.4X4XJ.>X4XT.I.J.J.D.#.P.p.Z.J.J.@.F.D.q.#.Z.#.D.p.O.W.;X  ",
"    S [ [ *.*.*.*.*.*.*.*.*.*.*.[ [ ;.,X,XT.>X4XT.p.#.F.J.q.#.I.p.p.p.J...D.D.F.@.p.q.F.q.*X*X  ",
"    S [ I [ [ [ [ *.[ [ [ I I [ I I ;.,X>XD.>X,XT.J.Z.O.p.I.Z.F.#.q.q.@.Z.D.p.#.p.#.F.q.E.*X*X  ",
"    S I I I [ I I I I I I I I I I I ;.>X>XF.>X,XI.Z.J.#.D.J.#.q.J.O.Z.p.q.p.Z.p.Z.O.O.#.*X*X*X  ",
"    S I I I I I I I I I I I I I I I *.,X,XJ.*X4XP.#.@.F.D.F.p.q.F.F.D...O.#.#.D.@.q.q.D.#.*X*X  ",
"    S I I I I I I I I I I I I I I I *.>X>XZ.;X>XI.Z.Z.D.J.>X;X;X*X;X*X;X*X*X;X*X*X*X*XXX*X&X&X  ",
"    S I I I I I I I I I I I I I I I [ >X>XXX,X,XP.Z.q.J.Z.Z.Z.D.#.#.XX;X;X*X*X*X*X*X*X*X*XXXXX  ",
"    S I I I I I I I I I I I I I I I *.;X;Xp.*X>X>X>X;X>X;X;X;X;X;X*X*X*X*X*X*XXX&X*X&XXXXXXXXX  ",
"    n H H H H H H H H H H H H H H H K ;X;Xq.&X>X}.W.}.E.E.I.}.W.P.R.E.J.T.E.T.R.T.R.P.}.XXXXXX  ",
"    a f f f f f f f f f f f f f f f z ;X;Xq.&X>Xp...#.@.#. .#...q.@.....} O.@.q.} .. .P.XXXXXX  ",
"      : : : : : : : : : : : : : : : 9 *X*XR.*X;XJ. .#.q.O.O.O. ...@. . .#.O.#...| O.#.O.D.R.}.  ",
"      . o o o o o o o o o o o o o o O *X*X*X;X;XD.O.#.#.q.q.O...@...} } ..q.O.O.| J.R.T.R.E.}.  ",
"                                      *X*X*X;X;XXXXXXX}.XX}.XXR.}.}.}.R.W.}.}.}.E.}.XX}.}.}.}.  ",
"                                            q.*X*X*X*X*X&X&X*XXXXXXXXXXXXXXXXX}.}.}.}.}.}.E.E.  ",
"                                            Z.*X*X*X&X*X&XXXXXXXXXXXXXXX}.}.}.}.}.}.}.E.}.E.E.  ",
"                                                                                                "
]