table=[
"48 48 99 2 ",
"   c None",
".  c #0B0B0B",
"X  c #0C0C0C",
"o  c gray5",
"O  c #0E0E0E",
"+  c gray6",
"@  c #101010",
"#  c #111111",
"$  c gray7",
"%  c #131313",
"&  c gray8",
"*  c #151515",
"=  c #161616",
"-  c gray9",
";  c #181818",
":  c #191919",
">  c gray10",
",  c #1B1B1B",
"<  c gray11",
"1  c #1D1D1D",
"2  c #1E1E1E",
"3  c gray12",
"4  c #202020",
"5  c gray13",
"6  c #222222",
"7  c #232323",
"8  c gray14",
"9  c #252525",
"0  c gray15",
"q  c #272727",
"w  c #282828",
"e  c gray16",
"r  c #2A2A2A",
"t  c gray17",
"y  c #2C2C2C",
"u  c #2D2D2D",
"i  c gray18",
"p  c #2F2F2F",
"a  c #313131",
"s  c #323232",
"d  c gray20",
"f  c #343434",
"g  c #353535",
"h  c #373737",
"j  c gray22",
"k  c #3C3C3C",
"l  c #3E3E3E",
"z  c gray25",
"x  c #414141",
"c  c gray26",
"v  c #434343",
"b  c #444444",
"n  c gray27",
"m  c #464646",
"M  c gray28",
"N  c #484848",
"B  c #494949",
"V  c #4B4B4B",
"C  c #4C4C4C",
"Z  c #4E4E4E",
"A  c #505050",
"S  c #515151",
"D  c #535353",
"F  c #555555",
"G  c #565656",
"H  c #585858",
"J  c #5A5A5A",
"K  c #5B5B5B",
"L  c gray36",
"P  c #5D5D5D",
"I  c #5F5F5F",
"U  c #606060",
"Y  c gray38",
"T  c #626262",
"R  c gray39",
"E  c #646464",
"W  c gray40",
"Q  c #676767",
"!  c #686868",
"~  c DimGray",
"^  c #6A6A6A",
"/  c #6C6C6C",
"(  c #6D6D6D",
")  c gray43",
"_  c #6F6F6F",
"`  c gray44",
"'  c #717171",
"]  c #727272",
"[  c gray45",
"{  c gray46",
"}  c #767676",
"|  c gray47",
" . c #797979",
".. c #7B7B7B",
"X. c #7C7C7C",
"o. c gray49",
"O. c #7E7E7E",
"+. c gray50",
"@. c gray51",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                    +.[ J V n n n n n n n n n n n n n n n n n n n n n F ) ..                    ",
"                @.F q e e e e u e e u e e u e e u e e u e e u e e u e e e q n +.                ",
"              +.u e u u u u u u u u u u u u u u u u u u u u u u u u u u u u e q )               ",
"            +.q e u u u u u u u u u u u u u u u u u u u u u u u u u u u u u u e q )             ",
"          +.e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e q {           ",
"          J q e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e e l           ",
"        ..q e e e e e e e e e e e e e q h [ j e e e e e e e e e e e e e e e e e e e q !         ",
"        ) q e q q e q q e q q e q q q J I   n q e q q e q q e q q e q q e q e e q q q I         ",
"        I q q q q q q q q q q q q l !       c q q q q q q q q q q q q q q q q q q q q c         ",
"        A q q q q q q q q q q e R           c q q q q q q q q q q q q q q q q q q q q d         ",
"        C 7 q q 7 q q 7 q 3 V R             A h h h h h h h h h h h h h j d 7 q q 7 q u         ",
"        C 7 7 7 q 7 7 7 u E                                               +.7 7 7 q 7 u         ",
"        V 7 7 7 7 7 7 F J                                                 +.3 7 7 7 7 u         ",
"        V 3 7 7 3 7 )                                                     +.3 7 7 3 3 u         ",
"        V 3 3 3 3 3 q !                                                   +.3 3 3 3 3 e         ",
"        n 3 3 3 3 3 3 ; l [                                               ..3 3 3 3 3 e         ",
"        n ; 3 3 3 3 3 ; ; ; J               R V V V V V V V V V V V V V C c ; 3 3 3 3 e         ",
"        n ; ; ; ; ; ; ; ; ; ; e )           h ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; e         ",
"        n ; ; ; ; ; ; ; ; ; ; ; = V )       h ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; e         ",
"        n = ; ; ; ; ; ; ; ; ; ; ; = 3 R     h = ; ; [ n = = ; ; ; ; ; ; ; ; ; ; ; ; ; q         ",
"        c = = = = = = = = = = = = = = = h ..u = = ;     R e = = = = = = = = = = = = = q         ",
"        c = = = = = = = = = = = = = = = = = = = = =         A = = = = = = = = = = = = q         ",
"        c = = = = = = = = = = = = = = = = = = = = =           R h @ = = = = = = = = = q         ",
"        c @ @ @ = @ d n n n n n n n n n n n n n n V               I 3 @ @ @ = @ @ = @ q         ",
"        c @ @ @ @ @ R                                               R n @ @ @ @ @ @ @ 7         ",
"        c @ @ @ @ O R                                                   R q @ @ @ @ @ 7         ",
"        c @ @ @ @ O R                                                     +.@ @ @ @ @ 7         ",
"        c O O O O O R                                                   E = O O O O O 7         ",
"        c O O O O O )                                               ..u O O O O O O O 7         ",
"        c O O O O O 3 e e e e e e e e e e e e e e u             ..F O O O O O O O O O 7         ",
"        c O O O O O O O O O O O O O O O O O O O O @           [ 3 O O O O O O O O O O 7         ",
"        A O O O O O O O O O O O O O O O O O O O O @       +.c . O O O O O O O O O O O d         ",
"        R O O O O O O O O O O O O O O O O O O O O @     E @ O O O O O O O O O O O O O C         ",
"        ) O O O O O O O O O O O O O O O O O O O O O { u . O O O O O O O O O O O O O . I         ",
"          V O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O e           ",
"          ) = O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O E           ",
"            ) O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O J             ",
"              ) = O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O O I               ",
"                ) c O O O O O O O O O O O O O O O O O O O O O O O O O O O O d !                 ",
"                    ! I V h d d d d d d d d d d d d d d d d d d d d h c J R                     ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]