table=[
"48 48 120 2 ",
"   c None",
".  c #3A87C2",
"X  c #3B87C2",
"o  c #3A87C3",
"O  c #3B87C3",
"+  c #3B88C2",
"@  c #3A88C3",
"#  c #3B88C3",
"$  c #3C88C3",
"%  c #3C89C3",
"&  c #3D89C3",
"*  c #3F8BC4",
"=  c #408BC4",
"-  c #418BC4",
";  c #418CC5",
":  c #428CC5",
">  c #448DC5",
",  c #458EC6",
"<  c #468EC6",
"1  c #478FC6",
"2  c #4890C7",
"3  c #4990C7",
"4  c #4A91C7",
"5  c #4C92C8",
"6  c #4D93C8",
"7  c #4F94C9",
"8  c #5095C9",
"9  c #5397CA",
"0  c #5598CB",
"q  c #5698CB",
"w  c #589ACC",
"e  c #599ACC",
"r  c #5A9BCC",
"t  c #5D9CCD",
"y  c #5E9DCD",
"u  c #5F9ECE",
"i  c #609ECE",
"p  c #609FCE",
"a  c #619FCE",
"s  c #629FCF",
"d  c #64A1CF",
"f  c #66A2D0",
"g  c #6DA6D2",
"h  c #76ACD5",
"j  c #7BAFD6",
"k  c #7CAFD7",
"l  c #81B2D8",
"z  c #88B6DA",
"x  c #88B7DA",
"c  c #89B7DA",
"v  c #89B7DB",
"b  c #8BB8DB",
"n  c #8DB9DC",
"m  c #8DBADC",
"M  c #8EBADC",
"N  c #92BDDD",
"B  c #94BEDE",
"V  c #95BFDE",
"C  c #96BFDF",
"Z  c #97BFDF",
"A  c #97C0DF",
"S  c #99C1E0",
"D  c #9AC1E0",
"F  c #9BC2E0",
"G  c #9DC3E1",
"H  c #9EC4E1",
"J  c #A1C6E2",
"K  c #A2C6E2",
"L  c #A3C7E2",
"P  c #A4C8E3",
"I  c #A6C9E3",
"U  c #ABCCE5",
"Y  c #B0CFE7",
"T  c #B1D0E7",
"R  c #B5D2E8",
"E  c #B7D3E9",
"W  c #BBD5EA",
"Q  c #BBD6EA",
"!  c #BED7EB",
"~  c #BFD8EB",
"^  c #C1D9EC",
"/  c #C5DBED",
"(  c #C9DEEE",
")  c #CDE0EF",
"_  c #CFE2F0",
"`  c #D0E2F0",
"'  c #D1E3F1",
"]  c #D2E4F1",
"[  c #D3E4F1",
"{  c #D4E4F1",
"}  c #D6E6F2",
"|  c #D8E7F3",
" . c #DDEAF4",
".. c #DEEBF4",
"X. c #DFECF5",
"o. c #E0ECF5",
"O. c #E1ECF5",
"+. c #E3EEF6",
"@. c #E4EEF6",
"#. c #E6F0F7",
"$. c #E7F0F7",
"%. c #E8F1F7",
"&. c #E9F2F8",
"*. c #EBF3F9",
"=. c #EFF5FA",
"-. c #F1F6FA",
";. c #F2F7FB",
":. c #F3F8FB",
">. c #F4F8FB",
",. c #F5F9FC",
"<. c #F7FAFC",
"1. c #F8FAFC",
"2. c #F8FBFD",
"3. c #F9FBFD",
"4. c #FBFDFE",
"5. c #FCFDFE",
"6. c #FDFDFE",
"7. c #FDFEFE",
"8. c #FEFEFE",
"9. c white",
"      X X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X X       ",
"    X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X     ",
"  X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X   ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X ",
"X X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X 4 f g s < X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 4 A  .9.9.9.9.9.} b = @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ @ c ;.9.9.9.9.9.9.9.9.9.o.t @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X % T 9.9.9.9.9.9.9.9.9.9.9.9.:.s X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ L 9.9.9.9.9.9.9.9.9.9.9.9.9.9.#.< @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X t 9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.S @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X P 9.9.9.9.9.9.} G V ^ 9.9.9.9.9.9.@.@ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ Q 9.9.9.9.9.H @ @ @ @ c 9.9.9.9.9.9.4 @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X S 9.9.9.9.~ @ @ X X @ % *.9.9.9.9.9.q X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ 4 #.9.9.o.4 @ @ @ @ @ @  .9.9.9.9.9.< @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X 4 M M 4 X X @ X X @ 4 2.9.9.9.9.o.@ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X 8 ( 9.9.9.9.9.S @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 8 S ` 9.9.9.9.9.9.%.< @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X s ,.9.9.9.9.9.9.9.;.s X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X Y 9.9.9.9.9.9.9.2.d @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ Q 9.9.9.9.9.9.9.9.=.j @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X M 9.9.9.9.9.9.9.9.9.9.N @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X % V  .9.9.9.9.9.9.9.9.9.h X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ = t V ;.9.9.9.9.9.*.= @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X s 9.9.9.9.9.9.l X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X r l t @ X X @ X X @ X X ` 9.9.9.9.9.R X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ U 9.9.9.j @ @ @ @ @ @ @ @ Q 9.9.9.9.9.[ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X k 9.9.9.9.;.5 X @ X X @ X X _ 9.9.9.9.9.[ X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X L 9.9.9.9.9.! @ @ X X @ X r 9.9.9.9.9.9.Q X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ c 9.9.9.9.9.9.U = @ @ @ q X.9.9.9.9.9.9.c @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X 5 2.9.9.9.9.9.9.*.R P ^ 2.9.9.9.9.9.9.>.< X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X P 9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.9.V X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X ; } 9.9.9.9.9.9.9.9.9.9.9.9.9.9.9./ % X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 4 } 9.9.9.9.9.9.9.9.9.9.9.9.9.^ ; @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ = L 2.9.9.9.9.9.9.9.9.9.;.M % X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 7 S | 4.9.9.9.,.) M < @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X * 8 r 7 % X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"X X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"X @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X ",
"  @ X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X @   ",
"    X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ @     ",
"      X X X @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X       "
]