table=[
"48 48 103 2 ",
"   c None",
".  c #3898C6",
"X  c #3899C7",
"o  c #3999C7",
"O  c #3999C8",
"+  c #399AC8",
"@  c #399AC9",
"#  c #399BCB",
"$  c #3A9BCB",
"%  c #399ECE",
"&  c #3A9ECE",
"*  c #3F9FCE",
"=  c #399FD0",
"-  c #39A1D3",
";  c #3AA1D3",
":  c #39A2D5",
">  c #3BA3D5",
",  c #39A3D7",
"<  c #3BA4D6",
"1  c #3AA4D7",
"2  c #3FA4D5",
"3  c #3CA5D7",
"4  c #3FA5D6",
"5  c #39A4D8",
"6  c #3AA5D9",
"7  c #3BA6DA",
"8  c #3DA6D9",
"9  c #3FA6D9",
"0  c #3CA6DA",
"q  c #3CA7DB",
"w  c #3DA7DB",
"e  c #3DA8DC",
"r  c #3EA8DC",
"t  c #3EA9DD",
"y  c #3FA9DD",
"u  c #3FAADE",
"i  c #40A0CE",
"p  c #41A1D1",
"a  c #42A2D0",
"s  c #43A3D1",
"d  c #40A2D3",
"f  c #42A3D2",
"g  c #42A4D3",
"h  c #43A5D5",
"j  c #42A6D7",
"k  c #44A5D4",
"l  c #46A5D4",
"z  c #47A6D5",
"x  c #47A7D6",
"c  c #46A7D7",
"v  c #48A7D6",
"b  c #49A8D7",
"n  c #4AA8D7",
"m  c #40A7DA",
"M  c #43A8D9",
"N  c #42A8DA",
"B  c #46A8D8",
"V  c #46A8D9",
"C  c #41A9DC",
"Z  c #41AADD",
"A  c #40AADE",
"S  c #40ABDF",
"D  c #41ABDF",
"F  c #42ABDE",
"G  c #43ABDE",
"H  c #44AADC",
"J  c #45ACDE",
"K  c #4CACDB",
"L  c #41ACE0",
"P  c #42ACE0",
"I  c #42ADE1",
"U  c #43ADE1",
"Y  c #47AFE1",
"T  c #44AEE2",
"R  c #44AFE3",
"E  c #45AFE3",
"W  c #45B0E4",
"Q  c #46B0E4",
"!  c #47B1E5",
"~  c #4CB0E0",
"^  c #4EB0E0",
"/  c #4CB2E3",
"(  c #48B1E4",
")  c #4BB2E5",
"_  c #48B2E6",
"`  c #49B3E7",
"'  c #4AB3E7",
"]  c #4AB4E8",
"[  c #4BB4E8",
"{  c #4BB5E9",
"}  c #4CB5E9",
"|  c #4CB6EA",
" . c #4DB6EA",
".. c #4DB7EB",
"X. c #4EB7EB",
"o. c #4EB8EC",
"O. c #4FB8EC",
"+. c #4FB9ED",
"@. c #50B9ED",
"#. c #50BAEE",
"$. c #51BAEE",
"%. c #51BBEF",
"&. c #52BBEF",
"                                  T T T T Q Q _                                                 ",
"                            T T T T T Q Q Q Q Q _ _ _                                           ",
"                        L L L L T T T T Q Q Q Q _ _ _ ] ]                     $.$.              ",
"                    4 4 4 N L L T T T Q Q Q Q Q _ _ _ ] ] ] }               $.$.$.              ",
"                  *       * p N L T T T T Q Q Q _ _ _ ] ] ] ] } }           $.$.$.$.            ",
"                              i p G T T T Q Q Q _ _ _ _ ] ] ] ] } }       o.$.$.$.$.            ",
"                                  * N T T Q Q Q _ _ _ _ ] ] ] } } } }   o.o.o.$.$.$.            ",
"                                      p J Q Q Q _ _ _ _ ] ] ] ] } } } o.o.o.o.$.$.$.            ",
"                                        p N Q Q Q _ _ _ _ ] ] ] ] } } o.o.o.o.$.$.$.            ",
"                                            h T Q _ _ _ ] ] ] ] } } o.o.} o.o.$.$.$.            ",
"                                              k T _ _ _ _ ] ] ] } } } } } o.o.$.$.$.            ",
"                                                k T _ _ _ _ ] ] ] } } } } o.o.o.$.$.            ",
"                                                  k T _ _ _ ] ] ] ] } } } o.o.o.$.$.            ",
"                                                    k _ _ _ ] ] ] ] } } } o.o.o.o.$.$.          ",
"                                                      B _ _ ] ] ] ] } } } } o.o.$.$.$.          ",
"                                                        _ _ ] ] ] ] } } } o.o.o.o.$.$.          ",
"                                                      _ _ _ ] ] ] ] } } } } o.o.o.$.$.          ",
"                                                      _ _ _ ] ] ] } } } } } o.o.o.o.$.          ",
"                                                    Q Q _ _ _ ] ] ] ] } } } } o.o.$.o.          ",
"                                                  Q Q _ _ _ _ ] ] ] ] } } } o.o.o.o.~           ",
"                                                Q Q Q _ _ _ _ ] ] ] _ _ ~ ~ ~ ~ ~ K             ",
"                                                H H H B B B k k k k v k n n                     ",
"                                                p                                               ",
"                                                                                                ",
"                                                                                                ",
"                                              T                                                 ",
"                    T T Q T T T T T T T T T T L                                                 ",
"            T T T T T T T T T T T T T T T T T g                                                 ",
"          L T T L T T T L T L T T L T T L L h                                                   ",
"          L L L L L L L L L L L L L L L L h                                                     ",
"          G L L L L L L L L L L L L L L N                                                       ",
"          G L L L L L L L L L L L L L L p                                                       ",
"          G L L G L L L G L L L L G L L                                                         ",
"          m G G G G r r G r L L G G G G G                                                       ",
"          8 G G G G G r G G G L G G G G G r                                                     ",
"            r r r r r r r r r r r r r r r r r                                                   ",
"            r r r r r r r r r r r r r r r r r r                                                 ",
"            r r r r r r r r r r r r r r r r r r r                                               ",
"            r r r r r r r r r r r r r r r r r r r r                                             ",
"            8 8 8 8 8 8 8 8 e r 8 8 8 8 8 e 8 8 8 8 8 8                                         ",
"            4 8 8 8 8 8 = 7 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8                                       ",
"            1 8 8 8 7 %   $ 1 8 8 8 8 8 8 8 e 8 8 8 8 8 8 8 8                                   ",
"            > 7 7 7 %       $ - 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7                               ",
"            - 7 7 -           X $ 1 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7       $                   ",
"              7 - $               X = 1 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 7 = $                     ",
"              $ X                     $ % > 7 7 7 7 7 7 7 7 7 7 7 > = $                         ",
"                                          $ $ % = > > > > > - = $ X                             ",
"                                                X X X X X X X                                   "
]