table=[
"48 48 88 1 ",
"  c None",
". c #3A87C2",
"X c #3B87C2",
"o c #3A87C3",
"O c #3B87C3",
"+ c #3B88C2",
"@ c #3A88C3",
"# c #3B88C3",
"$ c #3D89C3",
"% c #3E8AC4",
"& c #3F8AC4",
"* c #408BC4",
"= c #418BC4",
"- c #458EC6",
"; c #4890C7",
": c #4A91C7",
"> c #4E93C9",
", c #5094C9",
"< c #5296CA",
"1 c #5396CA",
"2 c #5497CA",
"3 c #5598CB",
"4 c #5799CB",
"5 c #5A9BCC",
"6 c #5B9BCD",
"7 c #5D9CCD",
"8 c #5D9DCD",
"9 c #5E9DCD",
"0 c #5F9ECE",
"q c #64A1CF",
"w c #65A1D0",
"e c #65A2D0",
"r c #66A2D0",
"t c #67A2D0",
"y c #6BA5D1",
"u c #6CA6D2",
"i c #6DA6D2",
"p c #70A8D3",
"a c #71A8D3",
"s c #72A9D3",
"d c #74AAD4",
"f c #77ACD5",
"g c #80B2D8",
"h c #83B4D9",
"j c #8AB8DB",
"k c #8CB9DB",
"l c #92BDDD",
"z c #99C1DF",
"x c #9FC5E1",
"c c #A0C5E2",
"v c #A7C9E4",
"b c #B1CFE7",
"n c #B4D1E8",
"m c #B7D3E9",
"M c #BBD5EA",
"N c #BBD6EA",
"B c #BDD7EB",
"V c #BFD8EB",
"C c #C3DAEC",
"Z c #C4DBED",
"A c #C9DEEE",
"S c #CADFEE",
"D c #CBDFEF",
"F c #CEE1F0",
"G c #CFE2F0",
"H c #D1E3F1",
"J c #D4E5F1",
"K c #D7E6F2",
"L c #DAE8F3",
"P c #E0ECF5",
"I c #E2EDF6",
"U c #E3EEF6",
"Y c #E4EFF6",
"T c #E5EFF7",
"R c #E7F0F7",
"E c #EBF3F9",
"W c #EDF4F9",
"Q c #EEF4F9",
"! c #EFF5FA",
"~ c #F1F6FA",
"^ c #F7FAFC",
"/ c #F9FBFD",
"( c #FAFCFD",
") c #FBFDFE",
"_ c #FDFDFE",
"` c #FDFEFE",
"' c #FEFEFE",
"] c white",
"   XXX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XXX   ",
"  X@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@X  ",
" XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XX ",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
"XXX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@XX@X%0i6@XX@X@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@@@gQ]]]Us@@@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XXd]]]]]])i@X@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@X*T]]]]]]]L@X@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@l]]]]]]]]]<@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@;~]]]]]]]]]iX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@v]]]]]]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@2/]]])K]]]]]s@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XXN]]]]bV]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@q]]]])3V]]]]]s@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@@G]]]]mXV]]]]]sX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@f]]]]]6XV]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@%U]]]]B@@V]]]]]s@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXXk]]]]]0XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XX-Q]]]]Z@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@c]]]]]w@@@V]]]]]s@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@X<^]]]]SX@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@Xm]]]]]yX@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@0]]]]]RsssssH]]]]]zw%@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@S]]]]]]]]]]]]]]]]]]]T3X@XX@XX@XX@XXX",
"@XX@XX@XX@Xi]]]]]]]]]]]]]]]]]]]]]CX@XX@XX@XX@XXX",
"@@@@@@@@@@@x]]]]]]]]]]]]]]]]]]]]]U@@@@@@@@@@@@@@",
"@XX@XX@XX@Xh]]]]]]]]]]]]]]]]]]]]]NX@XX@XX@XX@XXX",
"@XX@XX@XX@X$m]]]]]]]]]]]]]]]]]]]K>X@XX@XX@XX@XXX",
"@@@@@@@@@@@@@;0000000000S]]]]]j<@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XX@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@XX@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@XX@XXV]]]]]sX@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@@@@@m]]]]]w@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XX@XXg]]]]Q*X@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@@@@@@zUEGw@@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"@XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@",
"@XX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"XXX@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@XXX",
"X@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X",
" @X@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@X@ ",
"  X@XX@XX@X@XXX@XX@XX@XX@XX@XX@X@XX@XX@XX@XX@@  ",
"   XXX@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@X   "
]