table=[
"48 48 103 2 ",
"   c None",
".  c #3A87C2",
"X  c #3B87C2",
"o  c #3A87C3",
"O  c #3B87C3",
"+  c #3B88C2",
"@  c #3A88C3",
"#  c #3B88C3",
"$  c #3C88C3",
"%  c #3D89C3",
"&  c #3F8AC4",
"*  c #408BC4",
"=  c #418CC5",
"-  c #428CC5",
";  c #448DC6",
":  c #458EC6",
">  c #468EC6",
",  c #478FC6",
"<  c #4890C7",
"1  c #4A91C7",
"2  c #4D93C8",
"3  c #5094C9",
"4  c #5195C9",
"5  c #5497CA",
"6  c #5698CB",
"7  c #5799CB",
"8  c #599ACC",
"9  c #5A9BCC",
"0  c #5B9BCC",
"q  c #5B9BCD",
"w  c #5B9CCD",
"e  c #63A0CF",
"r  c #6BA5D1",
"t  c #6CA5D2",
"y  c #72A9D3",
"u  c #72A9D4",
"i  c #73AAD4",
"p  c #74AAD4",
"a  c #7AAED6",
"s  c #7BAFD6",
"d  c #7EB1D7",
"f  c #81B3D8",
"g  c #88B7DA",
"h  c #89B7DA",
"j  c #89B7DB",
"k  c #8AB8DB",
"l  c #90BBDD",
"z  c #92BDDD",
"x  c #94BEDE",
"c  c #9BC2E0",
"v  c #A0C5E2",
"b  c #A1C6E2",
"n  c #A2C6E2",
"m  c #A4C7E3",
"M  c #A5C8E3",
"N  c #A8CAE4",
"B  c #AACBE5",
"V  c #AECDE6",
"C  c #AFCEE6",
"Z  c #B1CFE7",
"A  c #B2D0E7",
"S  c #B4D1E8",
"D  c #B4D2E8",
"F  c #B6D2E8",
"G  c #B6D3E8",
"H  c #B8D4E9",
"J  c #B9D4E9",
"K  c #BBD6EA",
"L  c #BDD7EA",
"P  c #BDD7EB",
"I  c #BED7EB",
"U  c #C0D9EB",
"Y  c #C2DAEC",
"T  c #C4DBED",
"R  c #C8DDEE",
"E  c #C9DEEE",
"W  c #CADFEE",
"Q  c #CDE1EF",
"!  c #D0E2F0",
"~  c #D1E3F1",
"^  c #D5E5F2",
"/  c #D5E6F2",
"(  c #D6E6F2",
")  c #D8E7F3",
"_  c #DBE9F4",
"`  c #E0ECF5",
"'  c #E2EDF6",
"]  c #E3EEF6",
"[  c #EDF4F9",
"{  c #F0F6FA",
"}  c #F2F7FB",
"|  c #F3F7FB",
" . c #F3F8FB",
".. c #F4F8FB",
"X. c #F5F9FC",
"o. c #F6F9FC",
"O. c #F7FAFC",
"+. c #FBFCFD",
"@. c #FBFDFE",
"#. c #FCFDFE",
"$. c #FDFEFE",
"%. c #FEFEFE",
"&. c white",
"      X X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X X       ",
"    X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X     ",
"  X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X   ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X ",
"X X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X % 7 r r 8 % @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ 8 Z { &.&.&.&.X.I r @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X * B &.&.&.&.&.&.&.&.&.&.I , X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ , ! &.&.&.&.&.&.&.&.&.&.&.&._ < @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ % E &.&.&.&.&.&.&.&.&.&.&.&.&.&.T @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X l &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.y X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X - { &.&.&.&.&.+.H x B ..&.&.&.&.&.&.Y X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ d &.&.&.&.&.&.u @ @ @ 8  .&.&.&.&.&...% @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X V &.&.&.&.&.I @ X X @ X v &.&.&.&.&.&.2 X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ E &.&.&.&.&.u @ @ @ @ @ a &.&.&.&.&.&.5 @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X E &.&.&.&. .* @ X X @ X j &.&.&.&.&.&., X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X z &.&.&.&.V X @ X X @ X U &.&.&.&.&.] X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ & G &.&.) < @ @ @ @ @ 8 &.&.&.&.&.&.m @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ , 4 @ X X @ X X % ! &.&.&.&.&.&.7 X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X c &.&.&.&.&.&.G @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ t &.&.&.&.&.&...4 @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ 4 [ &.&.&.&.&.&.k X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X - ( &.&.&.&.&.&.Y @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ H &.&.&.&.&.&.] , @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X v &.&.&.&.&.&...w X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ j &.&.&.&.&.&.+.y X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ p +.&.&.&.&.&.&.j @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X e X.&.&.&.&.&.&.v X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ 5 [ &.&.&.&.&.&.H @ X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ < ] &.&.&.&.&.&.! * @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X & Q &.&.&.&.&.&.&.] ( ( ( ( ( ( ( E x & X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X v &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.G X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X @ { &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.X.@ @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ { &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&...@ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X v &.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.&.M X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ a A I I I I I I I I I I I I I I G f % @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"@ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ ",
"@ X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"X X X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X X X ",
"X @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X ",
"  @ X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ X @   ",
"    X @ X X @ X X @ X @ X X X @ X X @ X X @ X X @ X X @ X X @ X @ X X @ X X @ X X @ X X @ @     ",
"      X X X @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ @ X       "
]