table=[
"48 48 58 1 ",
"  c None",
". c #B74068",
"X c #B74168",
"o c #B74069",
"O c #B74169",
"+ c #B84169",
"@ c #B8446A",
"# c #B9456B",
"$ c #B9466B",
"% c #BA4A6E",
"& c #BB4C6F",
"* c #BD5372",
"= c #BE5373",
"- c #BE5574",
"; c #BF5976",
": c #C05B77",
"> c #C05C77",
", c #C05C78",
"< c #C15F79",
"1 c #C2627B",
"2 c #C2637B",
"3 c #C3657C",
"4 c #C4697F",
"5 c #C56A7F",
"6 c #C56C80",
"7 c #C67083",
"8 c #C77183",
"9 c #C77384",
"0 c #C87485",
"q c #C87686",
"w c #CA7C89",
"e c #CA7D89",
"r c #CB7E8A",
"t c #CD848E",
"y c #CE878F",
"u c #CF8A91",
"i c #CF8C92",
"p c #D08C92",
"a c #D08D92",
"s c #D19195",
"d c #D59E9C",
"f c #D6A09D",
"g c #D6A29E",
"h c #D6A39E",
"j c #D7A49F",
"k c #D7A5A0",
"l c #D9A9A2",
"z c #DAAEA5",
"x c #DCB3A7",
"c c #DEBBAC",
"v c #E4CCB5",
"b c #E5D0B7",
"n c #E5D1B8",
"m c #E6D2B8",
"M c #E6D2B9",
"N c #E7D5BA",
"B c #E7D7BB",
"V c #E8D8BC",
"  oooooooooooooooooooooooooooooooooooooooooooo  ",
" +o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+ ",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"o+o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+<rr4++;rrrrrrr6%+++o++o++o++o++o+o",
"++o++o++o+++o+yVVk++rVVBVVBVVMs@+o++o++o++o++o+o",
"oooooooooooo.oyBBkoorBBBBBBBBBBg+ooooooooooooooo",
"++o++o++o+++o+yVVk++rVVz2227jBVB7o++o++o++o++o+o",
"++o++o++o+++o+yVVk++rVVg++o++gVVxo++o++o++o++o+o",
"ooooooooooooo.yBBkoorBBgooooo2BBB@oooooooooooooo",
"++o++o++o+++o+yVVk++rVVg++o++@BVV:++o++o++o++o+o",
"++o++o++o+++o+yVVk++rVVg++o++obVV3++o++o++o++o+o",
"ooooooooooooooyBBkoorBBgooooooMBB2oooooooooooooo",
"++o++o++o+++o+yVVk++rVVg++o++&BVV=++o++o++o++o+o",
"++o++o++o+++o+yVVk++rVVg++o++0VVv+++o++o++o++o+o",
"ooooooooooooooyBBkoorBBgoooo@cBBdooooooooooooooo",
"++o++o++o+++o+yVVk++rVVl==-4xBVB>o++o++o++o++o+o",
"++o++o++o+++o+yVVk++rVVBVVBVVBVa+o++o++o++o++o+o",
"ooooooooooooooyBBkoorBBBBBBBBMy+oooooooooooooooo",
"++o++o++o+++o+2aa9++<aaiaaiu0&+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
"++o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"o+o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+o",
"oooooooooooooooooooooooooooooooooooooooooooooooo",
" +o++o++o+++o+o++o++o++o++o++o+++o++o++o++o++o+ ",
"  oo+o++o+++o+o++o++o++o++o++o+++o++o++o++o+oo  "
]