table=[
"48 48 130 2 ",
"   c None",
".  c #767676",
"X  c #777777",
"o  c gray47",
"O  c #2D5F9C",
"+  c #31639F",
"@  c #3566A2",
"#  c #3667A2",
"$  c #3A6AA5",
"%  c #3E6EA8",
"&  c #566C85",
"*  c #576C86",
"=  c #576D87",
"-  c #506988",
";  c #516A88",
":  c #4272AC",
">  c #4776AF",
",  c #4B7AB2",
"<  c #4F7DB5",
"1  c #5381B8",
"2  c #5785BC",
"3  c #5B89BF",
"4  c #5C89BF",
"5  c #608DC2",
"6  c #6490C6",
"7  c #6894CA",
"8  c #6C98CD",
"9  c #709CD0",
"0  c #759FD3",
"q  c #75A0D3",
"w  c #79A3D6",
"e  c #7DA7DA",
"r  c #81ABDD",
"t  c #92B2DB",
"y  c #86AFE0",
"u  c #8AB2E3",
"i  c #8EB6E6",
"p  c #9DBBE1",
"a  c #9DBBE2",
"s  c #9EBCE2",
"d  c #92BAE9",
"f  c #92BAEA",
"g  c #A1BEE3",
"h  c #A2BEE3",
"j  c #A4C0E3",
"k  c #A5C1E4",
"l  c #A6C1E4",
"z  c #A8C3E4",
"x  c #A9C3E5",
"c  c #A9C4E5",
"v  c #AAC5E5",
"b  c #ADC6E6",
"n  c #ADC7E6",
"m  c #AFC8E6",
"M  c #AFC8E7",
"N  c #B0C9E7",
"B  c #B1C9E7",
"V  c #B2CAE7",
"C  c #B3CBE8",
"Z  c #B4CCE8",
"A  c #B6CDE9",
"S  c #B7CEE9",
"D  c #BAD0EA",
"F  c #BED2EB",
"G  c #BFD3EB",
"H  c #B9D1EF",
"J  c #BFD3EC",
"K  c #BBD3F0",
"L  c #C1D5EC",
"P  c #C4D6ED",
"I  c #C5D7ED",
"U  c #C6D8EE",
"Y  c #C8D9EE",
"T  c #C9D9EE",
"R  c #C9DAEE",
"E  c #CBDBEF",
"W  c #CCDBEF",
"Q  c #CCDCEF",
"!  c #C3D8F2",
"~  c #C4D9F2",
"^  c #CDDDF0",
"/  c #CEDDF0",
"(  c #CFDEF0",
")  c #D0DEF0",
"_  c #D0DFF0",
"`  c #D0DFF1",
"'  c #D2E0F1",
"]  c #D3E0F1",
"[  c #D3E1F1",
"{  c #D4E1F2",
"}  c #D5E2F2",
"|  c #D6E3F2",
" . c #D7E3F3",
".. c #D8E4F3",
"X. c #D9E5F3",
"o. c #DAE5F3",
"O. c #DBE6F4",
"+. c #DCE7F4",
"@. c #DDE8F4",
"#. c #DDE8F5",
"$. c #DEE8F5",
"%. c #DFE9F5",
"&. c #E1EAF5",
"*. c #E1EAF6",
"=. c #E1EBF6",
"-. c #E2EBF6",
";. c #E3ECF6",
":. c #E4ECF6",
">. c #E4ECF7",
",. c #E4EDF7",
"<. c #E6EDF7",
"1. c #E6EEF7",
"2. c #E7EFF8",
"3. c #E8EFF8",
"4. c #E9EFF8",
"5. c #E9F0F8",
"6. c #EAF1F8",
"7. c #EBF1F9",
"8. c #ECF2F9",
"9. c #EDF2F9",
"0. c #EEF3F9",
"q. c #EFF4FA",
"w. c #F0F4FA",
"e. c #F0F5FA",
"r. c #F1F5FA",
"t. c #F2F6FB",
"y. c #F3F6FB",
"u. c #F4F7FB",
"i. c #F5F8FC",
"p. c #F7F9FC",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"      o                                                                                         ",
"      o X                                                                                       ",
"    X o o                                                                                       ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"    X o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                                                                         ",
"      o                                 f f f f f f f f                                         ",
"      o                                 i K ~ ! ! ! H i                                         ",
"      o                                 u p.p.p.u.e.e.u                                         ",
"    X o                                 y u.e.e.e.q.8.y                                         ",
"      o                                 r e.q.8.8.7.7.r                                         ",
"      o                                 e 8.7.7.3.>.>.e         e e e e e e e e                 ",
"      o         w w w w w w w w         w 3.>.;.-.-.@.w         w 7.e.e.e.8.-.w                 ",
"      o         0 z N N N M j q         0 -.-.@.@.O.X.q         q e.q.8.8.7.3.0                 ",
"      o         9 8.7.7.2.>.>.9         9 +.O.X. . .[ 9         9 8.7.7.2.>.>.9                 ",
"      o         8 3.>.>.-.-.@.8         8  . .[ ` ( U 8         8 3.>.>.-.-.@.8                 ",
"      o         7 >.-.@.@.O.X.7         7 ` ( Q R G S 7         7 ;.-.@.@.O.X.7                 ",
"    X o         6 @.+.X.X. .[ 6         6 R U G S C C 6         6 @.+.X.X. . .6                 ",
"      o         5 X. . .[ ( ( 5         5 S N M M M M 5         5 X. . .[ ( I 5                 ",
"      o         3 [ ` ( R R I 4         3 v v v v v v 4         4 [ ` ( R G S 3                 ",
"      o         2 W R U I J C 2         2 k k k k k k 2         2 R R G S N N 2                 ",
"      o         1 I L G S b b 1         1 g g g g g g 1         1 S M b b b b 1                 ",
"      o         < D C b z z z <         < s s s s s s <         < z z v z z v <                 ",
"      o         , k k k k k k ,         , s p p s p p ,         , k k k k k k ,                 ",
"    X o         > g g g g g g >         > s s s s s s >         > g g g g g g >                 ",
"      o         : s s s s s s :         : s p p s p p :         : s s s s s s :                 ",
"      o         % s s s s s s %         % s s s s s s %         % s s s s s s %                 ",
"      o         $ s p s p p p $         $ s p p s p p $         $ p p s p p p $                 ",
"      o         @ s p s p p p @         @ s p p s p p @         @ p p s p p p @                 ",
"      o         + t s s s s t +         + t s s s s t +         + t s s s s t +                 ",
"      o         O O O O O O O O         O O O O O O O O         O O O O O O O O *               ",
"      o         * ; ; ; ; ; ; *         * ; ; ; ; ; ; *         * ; ; ; ; ; ; *   o X           ",
"      o o o o o o o o o X X o o o o o X X o o o o o o X X o o o o o X X o o o o o o o o         ",
"                        X               X             X               X           X             ",
"                                                                                                ",
"                                                                                                "
]