table=[
"48 48 218 2 ",
"   c None",
".  c #7F8D70",
"X  c #E4A203",
"o  c #E3A105",
"O  c #E6A304",
"+  c #E5A404",
"@  c #E7A606",
"#  c #E8A603",
"$  c #EAA602",
"%  c #EBA805",
"&  c #E9A909",
"*  c #EAAB09",
"=  c #E9AD0F",
"-  c #ECAF0F",
";  c #F0A803",
":  c #F3AE06",
">  c #F2AE08",
",  c #F9B307",
"<  c #FBB406",
"1  c #FEB505",
"2  c #F8B70D",
"3  c #FFB809",
"4  c #FDBA0A",
"5  c #FBB90F",
"6  c #FFBE0C",
"7  c #E8AF17",
"8  c #ECB216",
"9  c #F1B516",
"0  c #F3B817",
"q  c #FBBA11",
"w  c #F9BA13",
"e  c #FBBB12",
"r  c #FFBE12",
"t  c #F9BC17",
"y  c #F0B81B",
"u  c #C9A536",
"i  c #CEAD3E",
"p  c #D4AD37",
"a  c #E6AF22",
"s  c #EEB825",
"d  c #F2B922",
"f  c #F4BD20",
"g  c #E2B632",
"h  c #FFC30A",
"j  c #FFC70F",
"k  c #FFCB0A",
"l  c #FFCE0B",
"z  c #FFCB0D",
"x  c #FFC80E",
"c  c #FFCF0C",
"v  c #FFCE0D",
"b  c #FFC815",
"n  c #FCC01B",
"m  c #FFC61D",
"M  c #FFC81A",
"N  c #FFCC1C",
"B  c #FFD011",
"V  c #FFD012",
"C  c #FFD217",
"Z  c #FFD616",
"A  c #FFD519",
"S  c #FFD41A",
"D  c #FFD61B",
"F  c #FFDA1D",
"G  c #F7C124",
"H  c #FDC623",
"J  c #FFCE21",
"K  c #FFCD27",
"L  c #FAC82B",
"P  c #FBC92B",
"I  c #FCC828",
"U  c #FDCA2C",
"Y  c #FFCF2D",
"T  c #FFD421",
"R  c #FFD920",
"E  c #FFD923",
"W  c #FFDD20",
"Q  c #FFD429",
"!  c #FFD02E",
"~  c #FFD52F",
"^  c #FFD92A",
"/  c #FFD82F",
"(  c #FFD931",
")  c #FFE025",
"_  c #FFE02B",
"`  c #FFE429",
"'  c #FFE12F",
"]  c #FFE72E",
"[  c #FFE033",
"{  c #FFE235",
"}  c #FFE934",
"|  c #FFE836",
" . c #FFE837",
".. c #FFEC35",
"X. c #FFEE35",
"o. c #FFEC36",
"O. c #FFEB38",
"+. c #FFF03A",
"@. c #9B975D",
"#. c #B59F46",
"$. c #A7A05D",
"%. c #838E6E",
"&. c #81967E",
"*. c #287EC6",
"=. c #668C93",
"-. c #769999",
";. c #5389AA",
":. c #4F8DB6",
">. c #4888BA",
",. c #628FA1",
"<. c #3089D3",
"1. c #488CC4",
"2. c #478FCD",
"3. c #4B90CB",
"4. c #4C90C9",
"5. c #4C90CA",
"6. c #4E93CD",
"7. c #4C92CE",
"8. c #4E93CE",
"9. c #5395CD",
"0. c #5495CC",
"q. c #5D9BCF",
"w. c #4598DF",
"e. c #4E98D8",
"r. c #5195D0",
"t. c #5799D0",
"y. c #5498D2",
"u. c #5D9DD2",
"i. c #569EDA",
"p. c #61A2D9",
"a. c #65A5DB",
"s. c #69A6D9",
"d. c #78AFDF",
"f. c #4099E5",
"g. c #4C9FE5",
"h. c #5AAAEC",
"j. c #65ABE6",
"k. c #68AAE2",
"l. c #6DADE5",
"z. c #73AFE2",
"x. c #7CB3E3",
"c. c #7BB5E6",
"v. c #75B2E8",
"b. c #75B4E9",
"n. c #78B6EB",
"m. c #7EB9EE",
"M. c #74C1FF",
"N. c #82B5DF",
"B. c #88BAE5",
"V. c #87BDEC",
"C. c #82BDF0",
"Z. c #8EC1EE",
"A. c #96C1E6",
"S. c #96C3E8",
"D. c #93C4EE",
"F. c #99C5E8",
"G. c #9BC5E9",
"H. c #9CC6EA",
"J. c #86C0F3",
"K. c #88C0F1",
"L. c #89C2F5",
"P. c #8CC5F6",
"I. c #82CAFF",
"U. c #8FC8F9",
"Y. c #96C6F0",
"T. c #9DCBF2",
"R. c #9CCDF7",
"E. c #90C8F8",
"W. c #95C9F8",
"Q. c #96CDFB",
"!. c #98CFFE",
"~. c #8DD0FF",
"^. c #9CD0FC",
"/. c #9DD2FF",
"(. c #A1C9EB",
"). c #A6CFF0",
"_. c #ABD3F5",
"`. c #A3D1F8",
"'. c #A1D5FF",
"]. c #A4D6FF",
"[. c #AAD6FB",
"{. c #A7D9FF",
"}. c #ADD9FF",
"|. c #ACDDFF",
" X c #B1D8FA",
".X c #B0DFFF",
"XX c #B5DDFF",
"oX c #BADCF9",
"OX c #B9DFFF",
"+X c #B5E2FF",
"@X c #B4E6FF",
"#X c #B8E6FF",
"$X c #BCE4FF",
"%X c #BFE6FF",
"&X c #BDE9FF",
"*X c #C1E2FD",
"=X c #C4E6FF",
"-X c #C1EAFF",
";X c #C3EBFF",
":X c #C8EAFF",
">X c #CEEAFF",
",X c #C8EFFF",
"<X c #D1EFFF",
"1X c #D0F5FF",
"2X c #D8F0FF",
"3X c #DBF4FF",
"4X c #D7F8FF",
"5X c #DAFAFF",
"6X c #E0F8FF",
"7X c #E4F8FF",
"8X c #E4FBFF",
"9X c #E8FEFF",
"0X c #EEFFFF",
"qX c #F2FFFF",
"wX c #F7FFFF",
"eX c #FAFFFF",
"rX c #FEFFFF",
"tX c white",
"                                                                                                ",
"                                                                                                ",
"                                                                      b.E.j.                    ",
"                                                                    b.tXwXH.                    ",
"                                                                  i.3XtX>XN.9.                  ",
"                                                                  V.tX8XY.0.                    ",
"                                  G.G.H.H.S.                    e.6XwX}.p.A.                    ",
"                              B.oX9XtXtXtXtX2X(.                P.wX-Xv.5.                      ",
"                            H.6XqXwXeXtXtXtXtXtX2XA.          w.1X5XJ.2.G.                      ",
"                          H.2X6X8X9X0XqXwXtXtXtXtXtXoXS.      I.5X^.g.8.                        ",
"                        N.=X>X<X2X3X8X9X0XqXwXtXtXtXtXwX).  f.@X@Xh.*.                          ",
"                      a._.oX*X=X>X<X2X3X6X9X0XqXwXtXtXtXtXZ.M.@XM.<.8.                          ",
"                      N._._. XoXOX*X=X>X<X3X6X8X0X0XwXeXtX}.I.~.g.*.                            ",
"                    q.Z.Y.T.T.`._. XXXOX%X=X:X<X2X6X9X0XqXqXP.h.<.s.z.                          ",
"                  5.s.d.V.Z.Y.Y.T.`.`.[.}.XXOX%X-X:X<X4X8X9X0X<X2XtX9XD.                        ",
"                  5.u.t.u.d.V.Z.Z.Y.R.R.`.[.}..X+X%X%X-X,X<X5X9X0XeXtXtX<XB.                    ",
"                  -.0.u.t.0.p.x.V.V.Z.Y.W.R.`.].{.}..X+X%X%X-X,X1X6X9XwXtXeX Xc.                ",
"                  b @.:.t.u.t.t.d.Z.V.V.Z.P.W.R.^.'.].}..X+X#X&X-X,X1X5X9XwXtX8Xb.              ",
"                V : 1 M . 1.t.t.0.u.Y.Y.V.C.K.P.W.Q.^.^.].{.|..X+X#X&X-X,X4X9XwX9Xb.            ",
"              x 3 > c ; 1 s =.3.t.t.8.d. XR.m.C.K.P.U.W.!.^.].{.|..X+X#X&X-X,X4X0X,Xz.          ",
"            Z x o c 3 % l $ 1 i ;.8.t.r.8.Y.:X[.m.C.J.P.U.W.!.^.'.{.|..X+X#X&X-X1X9XK.          ",
"            A & j x o c 3 % l @ < $.>.r.t.8.u._.2XY.m.C.J.P.U.Q.!.^.].{.|..X@X#X&X1X#X          ",
"          F e e Z & j x @ c , < k O d &.1.t.r.8.d.6X8XW.m.C.J.P.U.Q.^.'.].{.|..X@X&X-Xa.        ",
"        ' N - F e e Z & j x @ V , < k o g =.2.t.r.8.x.2XOXK.C.J.L.P.W.!.^.'.{.|..X+X#Xk.        ",
"      X.R 8 R N - F e 5 Z & j x X V : < x X u ;.8.t.r.8.Y.>X[.m.C.J.P.U.W.!.^.'.{.|.|.k.        ",
"    X.] y T W 8 T N - F e 5 Z & j h $ c : 1 h & $.>.t.t.8.8.Z.OXW.m.C.J.P.U.Q.!.^.].'.a.        ",
"    X.H K ] f J ) 8 C N - A r 2 Z & j h $ c ; x ; a &.1.t.r.8.u.Z.`.C.C.C.L.P.U.Q.^.U.i.        ",
"  X./ I X.K H ] n M ) 8 C A - A r 2 Z & j 6 3 h % c $ p =.3.t.r.8.p.V.K.m.C.J.L.P.W.l.          ",
"      O.[ G | Q f ] m n ) 9 M A - A r 2 C : V $ 3 6 % l O #.;.r.t.8.8.p.v.n.m.C.K.J.e.          ",
"          | | f ] ^ y ` m t ) 9 b A & A r x 6 > C @ x 3 < k o @.1.t.t.8.r.p.v.n.m.p.            ",
"            Y [ X.f _ _ y _ J 0 ) 0 b A r A & V 6 > C @ x 3 < x u &.1.t.r.8.t.l.l.8.            ",
"                ! / X.G ^ _ y ) J 9 ) e R r e A @ V 6 > C O j , 1 h #.,.3.t.r.t.5.              ",
"                    ~ K X.H Q ] y R T N R = F r e A @ V 3 3 V o c : < 6 @.:.8.3.5.              ",
"                        ' I X.K K ] m ` f m R = A r e A @ V 3 3 x @ c ; < e %.                  ",
"                          | | G | Q _ ^ y ) n m R = A r e Z @ V , 3 x $ c $                     ",
"                              { | Q X.f ^ _ 8 ) m n W = A r 5 A O V , 3 h %                     ",
"                                  +./ I X.G Q _ 8 ) m n W = A r 5 A O V :                       ",
"                                    L | [ G | H K _ 8 W m t W = A r 5 V @                       ",
"                                        L | | f | K H _ 8 R N t W = A r                         ",
"                                            U [ | f ] K H ` 8 R N t W =                         ",
"                                                ~ / X.f _ Q n ` 9 T N %                         ",
"                                                  X.( K X.f _ ^ f ` y                           ",
"                                                      X.[ I X.G ^ ^ 7                           ",
"                                                          O.| G | H                             ",
"                                                              ' | s                             ",
"                                                                Y d                             ",
"                                                                                                ",
"                                                                                                "
]