table=[
"64 64 121 2 ",
"   c None",
".  c #E73C3C",
"X  c #E73D3D",
"o  c #E73E3E",
"O  c #E83E3C",
"+  c #E83E3D",
"@  c #E83E3E",
"#  c #E83F3F",
"$  c #E94040",
"%  c #E84141",
"&  c #E94141",
"*  c #E94241",
"=  c #E94242",
"-  c #E94342",
";  c #E94343",
":  c #E94443",
">  c #E94444",
",  c #E94544",
"<  c #E94545",
"1  c #EA4645",
"2  c #E94646",
"3  c #EA4646",
"4  c #EA4746",
"5  c #EA4747",
"6  c #EA4847",
"7  c #E94848",
"8  c #EA4848",
"9  c #EA4948",
"0  c #EA4A49",
"q  c #EA4A4A",
"w  c #EA4B4A",
"e  c #EB4B4A",
"r  c #EB4C4A",
"t  c #EB4C4B",
"y  c #EB4D4B",
"u  c #EA4C4C",
"i  c #EB4D4C",
"p  c #EB4E4C",
"a  c #EB4E4D",
"s  c #EB4F4D",
"d  c #EB4F4E",
"f  c #EA504D",
"g  c #EB504E",
"h  c #EB504F",
"j  c #EC504F",
"k  c #EC514F",
"l  c #EC5150",
"z  c #EC5250",
"x  c #EC5251",
"c  c #EC5351",
"v  c #EC5352",
"b  c #EC5452",
"n  c #EC5453",
"m  c #EC5553",
"M  c #EC5554",
"N  c #EC5654",
"B  c #ED5654",
"V  c #EC5655",
"C  c #ED5755",
"Z  c #ED5855",
"A  c #ED5856",
"S  c #ED5956",
"D  c #EC5957",
"F  c #ED5957",
"G  c #EC5A58",
"H  c #ED5A58",
"J  c #ED5B59",
"K  c #EE5C59",
"L  c #ED5D5B",
"P  c #EE5C5A",
"I  c #EE5D5A",
"U  c #EE5D5B",
"Y  c #EE5E5B",
"T  c #ED5E5C",
"R  c #EE5E5C",
"E  c #EE5F5C",
"W  c #EE5F5D",
"Q  c #EC5F5E",
"!  c #ED5F5E",
"~  c #EE605D",
"^  c #EC605F",
"/  c #EE615E",
"(  c #EF615F",
")  c #EE625E",
"_  c #EF625F",
"`  c #ED6260",
"'  c #EF6260",
"]  c #EF6360",
"[  c #EE6563",
"{  c #EF7B79",
"}  c #EF7D7A",
"|  c #EF7C7B",
" . c #F08280",
".. c #F08482",
"X. c #F19997",
"o. c #F19A98",
"O. c #F29C9A",
"+. c #F29D9B",
"@. c #F19F9E",
"#. c #F2A5A3",
"$. c #F2A6A4",
"%. c #F3A8A6",
"&. c #F5C4C2",
"*. c #F5C6C4",
"=. c #F5C6C5",
"-. c #F5C7C5",
";. c #F5C7C6",
":. c #F5C8C5",
">. c #F5C8C6",
",. c #F5C8C7",
"<. c #F6C9C7",
"1. c #F6CAC9",
"2. c #F6CBCA",
"3. c #F6CCCB",
"4. c #F7DEDC",
"5. c #F7E4E2",
"6. c #F7E5E3",
"7. c #F7E6E4",
"8. c #F7E7E5",
"9. c #F8E9E7",
"0. c #F8EDEB",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                            < < ' ' ) ) ) ) ) ) ! ! ! K K K K K G G G G S S S C S                               ",
"                                          7 = # ' ) ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C                           ",
"                                        7 < = # ) ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C                           ",
"                                      a 7 < = # ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m                         ",
"                                    h t 7 < = # ) ) ) ) ! ! K K K K K K G G G G S S S S S C C C C m m m                         ",
"                                  v a t 7 < = # ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m                         ",
"                                C v a t 7 < = # ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v                         ",
"                              G C v a t 7 < = = ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v                         ",
"                            K S C v a t 7 < = 6 ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v                         ",
"                          ! K S C v a t 7 < = C ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v                         ",
"                        ) ! K S C v a t 6 < j ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v                         ",
"                        ) ! K S C v a t a C ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j                         ",
"                        ' ' ) ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h                         ",
"                        ' ) ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h h                         ",
"                        ) ) ) ) ! ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h h a                         ",
"                        ) ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h h a a                         ",
"                        ) ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h h a a a                         ",
"                        ) ) ) ! ! ! K K K K K G G G G S S S S S C C C C m m m m v v v v v j h h a a a a                         ",
"                        ) ) ! ! K K 3.0.0.0.0.4.%.! S S 2.0.0.8.>...C m m m 2.0.0.0.0.0.0.>.h a a a a a                         ",
"                        ) ! ! ! K K 0.0.0.0.0.0.0.%.S S 0.0.0.0.0.0.#.m m m 0.0.0.0.0.0.0.*.a a a a a a                         ",
"                        ! ! ! K K K 0.0.G G G } 0.4.S S 0.0.C [ O.9.0. .m v 0.0.v v j h h a a a a a a t                         ",
"                        ! ! K K K K 0.0.G G G S 0.0.S S 0.0.C C m O.0.*.v v 0.0.v j h h a a a a a a t t                         ",
"                        ! K K K K K 0.0.G G S S 0.0.S C 0.0.C m m ' 0.5.v v 0.0.j h h a a a a a a t t t                         ",
"                        K K K K K G 0.0.G S S S 0.0.C C 0.0.m m m m 0.0.v v 0.0.h h a a a a a a t t t 7                         ",
"                        K K K K G G 0.0.S S S S 0.0.C C 0.0.m m m v 0.0.v v 0.0.h a a a a a a t t t 7 7                         ",
"                        K K K G G G 0.0.S S S S 0.0.C C 0.0.m m v v 0.0.v j 0.0.a a a a a a t t t 7 7 7                         ",
"                        K K G G G G 0.0.S S S C 0.0.C m 0.0.m v v v 0.0.j h 0.0.0.0.0.0.0.>.t t 7 7 7 7                         ",
"                        K G G G G S 0.0.S S C { 0.4.m m 0.0.v v v v 0.0.h h 0.0.0.0.0.0.0.*.t t t 7 7 7                         ",
"                        G G G G S S 0.0.0.0.0.0.0.#.m m 0.0.v v v v 0.0.h a 0.0.a a a t t t 7 7 7 7 7 7                         ",
"                        G G G S S S 0.0.0.0.0.4.$.S m m 0.0.v v v j 0.0.a a 0.0.a a t t t 7 7 7 7 7 7 7                         ",
"                        G G S S S S 0.0.C C C m m m m v 0.0.v v j h 0.0.a a 0.0.a t t t 7 7 7 7 7 7 7 6                         ",
"                        G S S S S S 0.0.C C m m m m v v 0.0.v j h h 0.0.a a 0.0.t t t 7 7 7 7 7 7 7 6 <                         ",
"                        S S S S S C 0.0.C m m m m v v v 0.0.j h h a 0.0.a a 0.0.t t 7 t 7 7 7 7 7 6 < <                         ",
"                        S S S S C C 0.0.m m m m v v v v 0.0.h h a ) 0.5.a a 0.0.t 7 t 7 7 7 7 7 6 < < <                         ",
"                        S S S C C C 0.0.m m m v v v v v 0.0.h a a o.0.&.a t 0.0.t t 7 7 7 7 7 6 < < < <                         ",
"                        S S C C C C 0.0.m m v v v v v j 0.0.a ! X.9.0.} t t 0.0.t 7 7 7 7 7 6 6 < < < <                         ",
"                        S C C C C m 0.0.m v v v v v j h 0.0.0.0.0.0.@.t t t 0.0.7 7 7 7 7 6 < < < < < <                         ",
"                        C C C C m m >.>.v v v v v j h h >.0.0.8.&.} t t t 7 *.*.7 7 7 7 6 6 < < < < < <                         ",
"                        C C C m m m m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < 6 < < < < < <                         ",
"                        C C m m m m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < :                         ",
"                        C m m m m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : =                         ",
"                        m m m m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = =                         ",
"                        m m m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = =                         ",
"                        m m v v v v v j h h a a a a a a t t t t 7 7 7 7 7 7 6 < < < < < < < < : = = = =                         ",
"                        m v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 6 < < < < < < < : = = = = =                         ",
"                        v v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 6 < < < < < < < : = = = = = =                         ",
"                        v v v v j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = =                         ",
"                        v v v j h h a a a a a a t t t t 7 7 7 7 7 7 6 6 < < < < < < < : = = = = = = = =                         ",
"                        v v j h h a a a a a a t t t 7 t 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = #                         ",
"                        v j h h a a a a a a t t t t 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # #                         ",
"                        j h h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # # #                         ",
"                        a h a a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # # # X                         ",
"                        h a a a a a a t t t 7 t 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # # # # #                         ",
"                          a a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # # # # #                           ",
"                          a a a a t t t 7 7 7 7 7 7 7 6 < < < < < < < < : = = = = = = = = # # # # # X                           ",
"                              a t t t 7 7 7 7 7 7 7 6 6 < < < < < < < : = = = = = = = = # # # X #                               ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                ",
"                                                                                                                                "
]