table=[
"48 48 124 2 ",
"   c None",
".  c #BC7D19",
"X  c #BD7E19",
"o  c #BF7E1A",
"O  c #BF7F1B",
"+  c #CF8817",
"@  c #C18019",
"#  c #C1811B",
"$  c #C48219",
"%  c #C68318",
"&  c #C78418",
"*  c #CA8518",
"=  c #CD8618",
"-  c #CB871C",
";  c #C8861F",
":  c #CE891C",
">  c #DA8D16",
",  c #D38A19",
"<  c #D28B1C",
"1  c #D28C1C",
"2  c #D18C1F",
"3  c #DF9218",
"4  c #DE931D",
"5  c #E09115",
"6  c #E19216",
"7  c #E19217",
"8  c #E29317",
"9  c #E39417",
"0  c #E39418",
"q  c #E49518",
"w  c #E59619",
"e  c #E5961A",
"r  c #E6971A",
"t  c #E6971B",
"y  c #E3961D",
"u  c #E3971F",
"i  c #E7981B",
"p  c #E8991C",
"a  c #E99A1D",
"s  c #EA9B1E",
"d  c #EB9C1F",
"f  c #EC9D1F",
"g  c #D38E20",
"h  c #D99121",
"j  c #DF9520",
"k  c #E69A22",
"l  c #E99C23",
"z  c #EC9D20",
"x  c #ED9E21",
"c  c #EE9F21",
"v  c #ED9E22",
"b  c #EE9F22",
"n  c #EE9F23",
"m  c #EFA023",
"M  c #EFA024",
"N  c #F0A124",
"B  c #F0A125",
"V  c #F1A224",
"C  c #F1A225",
"Z  c #F2A326",
"A  c #F2A327",
"S  c #F3A427",
"D  c #F4A528",
"F  c #F5A628",
"G  c #F5A629",
"H  c #F5A62A",
"J  c #F6A72A",
"K  c #F7A82B",
"L  c #F8A82B",
"P  c #F8A92C",
"I  c #F9AA2C",
"U  c #F9AA2D",
"Y  c #378DB6",
"T  c #378EB8",
"R  c #3793BF",
"E  c #3794C1",
"W  c #3795C2",
"Q  c #3896C3",
"!  c #3899C8",
"~  c #3999C8",
"^  c #389AC9",
"/  c #3B9BCA",
"(  c #389CCC",
")  c #399ECF",
"_  c #3C9DCC",
"`  c #3BA0D2",
"'  c #3AA3D5",
"]  c #39A4D8",
"[  c #3AA5D9",
"{  c #3AA5DA",
"}  c #3CA7DB",
"|  c #3DA8DC",
" . c #3EA9DD",
".. c #3FAADE",
"X. c #40A2D2",
"o. c #41A6D8",
"O. c #40A8DA",
"+. c #40ABDF",
"@. c #44AADD",
"#. c #41ACE0",
"$. c #42ADE1",
"%. c #46AEE1",
"&. c #47AEE1",
"*. c #44AFE3",
"=. c #45B0E4",
"-. c #47B1E5",
";. c #48B2E6",
":. c #49B3E7",
">. c #4AB4E8",
",. c #4BB5E9",
"<. c #4CB5E9",
"1. c #4CB6EA",
"2. c #4DB6EA",
"3. c #4DB7EB",
"4. c #4EB8EC",
"5. c #4FB8EC",
"6. c #4FB9ED",
"7. c #50B9ED",
"8. c #50BAEE",
"9. c #51BAEE",
"0. c #51BBEF",
"q. c #52BBEF",
"w. c #53BCF0",
"e. c #54BDF1",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                P P P P P P P P P P P                                           ",
"                          P P P P P P P P P P P P P P P K K                                     ",
"                      K P P P P P P P P P K K K P P P K K K P D                                 ",
"                  P P P P P P P P K P L K L L K P P D L D D D D K                               ",
"                P P P P K L K L L K L L D L D D D D D D D D D D D D D                           ",
"              K K K K K K D D D D D D D D D D D D D D D D D D D D D D D                         ",
"            K L D L L D D D D D D D D D D D D D D D D D D D D D D D D D D                       ",
"          D D D D D D D D D D D D D D D D D D D D D D D D D D D D S S S S S                     ",
"        K D D D D D D D D D D D D D D D D D D D S S S S S S S S S S S Z Z Z                     ",
"      D D D D D D D D D D D D D D D D D S D D S S S S S S Z S S Z Z Z Z Z Z D                   ",
"      D D D D D D D D D D D S D D D S D S S S Z S S Z Z Z Z Z Z Z Z Z Z Z Z Z m                 ",
"    D D D D D S S S S S S S S S S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z                   ",
"    S D D S S S S S S S Z S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z m Z           e.e.w.    ",
"  D S S S S S S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z           w.w.e.e.w.    ",
"  S Z S Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z M Z Z m b             e.e.w.e.e.w.w.  ",
"  Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z M M M m m b b m b             w.w.w.w.w.w.w.w.w.  ",
"Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z Z M Z Z M m m m m b m m m b             9.e.e.w.w.w.w.w.9.9.9.  ",
"Z Z Z Z Z Z Z Z Z Z Z Z M Z M m m m m m m m m b m b b m b           9.w.w.w.9.9.9.9.6.9.9.6.6.  ",
"Z Z Z Z Z M M M M m m m m m m b b b b b b b b b b b m           w.9.9.9.6.6.6.6.6.6.6.6.6.6.6.9.",
"Z Z M m m m m m m m m m b b b b b b b b b b b b b             9.9.6.6.6.6.6.6.6.6.6.<.<.<.<.<.<.",
"m m m m m b m m b b b b b b b b b b b b b b f             9.6.6.6.6.6.6.6.<.<.<.<.<.<.<.,.,.,.,.",
"b b b b b b b b b b b b b b b b b b b b b b           6.6.6.6.<.<.<.<.<.<.<.<.,.,.,.,.,.,.,.:.:.",
"z b b b b b b b b b b b b b b b b b b b b b b       9.<.<.<.<.<.<.,.,.,.,.,.,.,.,.:.:.:.:.:.:.-.",
"k b b b b b b b b b b b z b b b b d b d d d s s       <.,.,.,.,.,.,.,.:.:.:.:.:.:.:.:.-.-.-.-.&.",
"y b b b b b b b b b d d s d d d d d d d d d s s         ,.:.:.:.:.:.:.:.:.-.-.-.-.-.-.-.-.&.&.@.",
"h b b b b d b d d d d d d d d d d d s s s s s s f       &.:.:.-.-.-.-.-.-.-.-.&.&.&.&.&.&.&.$.o.",
"  d d d d d d d d d d s d s s s s s s s s s s s s s       &.-.-.-.&.&.&.&.&.&.&.$.$.$.$.$.$.$.X.",
"  j d d d d d d s s s s s s s s s s s s s s s s s s         &.&.$.$.$.$.$.$.$.$.$.$.$.+.+.+. .  ",
"  g s s s s s s s s s s s s s s s s s s s s s s s s i       o.$.$.$.$.$.$.+.+.+.+. . . . . .'   ",
"    y s s s s s s s s s s s s s s s s s s s s s i i i i       O.+.+.+. . . . . . . . . . . ./   ",
"    2 s s s s s i i s s s s s s s s s s i i r r r r r r          . . . . . . . . .} } } } {     ",
"      4 s s s s i i i i i r s i i i i i r r r r r r r r i       _  . .} } } } { { { { { { /     ",
"      ; r s s s i r i i r r r r r r r r r r r r r r r r r y       ` { { { { { { { { { { '       ",
"        ; r i i r r r r r r r r r r r r r r r r r r r r r r         ' { { { { { { { { { E       ",
"          < r r r r r r r r r r r r r r r r r r r r r r r 0 r       Q { { { { { { { { /         ",
"            2 r r r r r r r r r r r 9 r r r r r r r 0 9 9 0 9 9       ( { { { { { { (           ",
"              : 0 r r r r r r r r r 0 0 0 0 0 0 0 9 9 8 8 8 8 8         ' { { { { ( T           ",
"                ; 3 r r 0 r 0 9 9 0 9 9 9 9 9 8 9 8 8 8 8 8 8 8 8       R { { { ( T             ",
"                  O , 8 0 9 9 9 9 8 9 8 8 8 8 8 8 8 8 8 8 8 8 > %         E { / Y               ",
"                      # , 3 8 8 8 8 8 8 8 8 8 8 8 8 8 8 8 > % O             E                   ",
"                          O * , 3 8 8 8 8 8 8 8 8 8 > + % O                                     ",
"                                O # & * = = * & % O O                                           ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]