table=[
"48 48 112 2 ",
"   c None",
".  c #7AA448",
"X  c #7BA448",
"o  c #7BA548",
"O  c #7BA549",
"+  c #7BA649",
"@  c #7CA649",
"#  c #7CA54A",
"$  c #7DA74A",
"%  c #7CA64B",
"&  c #7DA64C",
"*  c #7DA84A",
"=  c #7EA94A",
"-  c #7FAB4B",
";  c #80AC4C",
":  c #81AD4C",
">  c #82AF4D",
",  c #83B04D",
"<  c #84B14E",
"1  c #85B24F",
"2  c #86B44F",
"3  c #81A951",
"4  c #82AA53",
"5  c #83AA54",
"6  c #86AC58",
"7  c #86AC59",
"8  c #86AD59",
"9  c #87B550",
"0  c #88B650",
"q  c #88B751",
"w  c #8AB952",
"e  c #8DBD53",
"r  c #8FBF54",
"t  c #8BB05F",
"y  c #8CB25F",
"u  c #8DB162",
"i  c #93B56A",
"p  c #95B76E",
"a  c #96B76E",
"s  c #9BBB76",
"d  c #9CBB76",
"f  c #9CBC77",
"g  c #9EBD7A",
"h  c #A0BE7C",
"j  c #91C255",
"k  c #92C456",
"l  c #94C657",
"z  c #95C758",
"x  c #94C45B",
"c  c #96C858",
"v  c #96C958",
"b  c #97CA59",
"n  c #97CB59",
"m  c #98CC5A",
"M  c #99CD5A",
"N  c #9ACE5B",
"B  c #9CCF5F",
"V  c #99C662",
"C  c #A0D165",
"Z  c #A1D167",
"A  c #A7D371",
"S  c #A7C485",
"D  c #ACC68C",
"F  c #ACC68D",
"G  c #AEC78F",
"H  c #B4CC98",
"J  c #B9CF9E",
"K  c #B9CF9F",
"L  c #BADD90",
"P  c #BED3A6",
"I  c #C0E09A",
"U  c #C8D9B3",
"Y  c #CBDBB7",
"T  c #CDDDBA",
"R  c #CFDEBD",
"E  c #C6E3A2",
"W  c #CBE6AB",
"Q  c #D0E0BD",
"!  c #D5E2C5",
"~  c #D5E2C6",
"^  c #D7E3C7",
"/  c #D6E9C0",
"(  c #D9ECC1",
")  c #D7E4C8",
"_  c #D7E4C9",
"`  c #DAE6CD",
"'  c #DDE8D1",
"]  c #DEE8D1",
"[  c #DFE9D2",
"{  c #E1F0CE",
"}  c #E2EBD7",
"|  c #E2EBD8",
" . c #E5F2D6",
".. c #E7F1DB",
"X. c #EAF4DD",
"o. c #EBF1E3",
"O. c #F1F6EC",
"+. c #F2F6ED",
"@. c #F4F9EE",
"#. c #F4F7F0",
"$. c #F4F8F0",
"%. c #F6F9F3",
"&. c #F7F9F4",
"*. c #F7FAF4",
"=. c #F8FBF4",
"-. c #F8FAF5",
";. c #F8FCF4",
":. c #FBFCFA",
">. c #FDFEFC",
",. c #FDFEFD",
"<. c #FEFEFE",
"1. c white",
"                                      M M M M M M M M M M                                       ",
"                                M M M M M M M M M M M M M M M M                                 ",
"                          M M M M M M M M M M M M M M M M M M M M M M                           ",
"                      M M M M M M M M M M M M M M M M M M M M M M M M M M                       ",
"                    M M M M M M M M M M M M M M M M M M M M M M M M M M M M                     ",
"                  M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M                   ",
"                M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M                 ",
"              M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M               ",
"            M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M             ",
"          M M M M M M M M M M M B L E E E E E E E E E E E E E E E E I C M M M M M M M           ",
"        M M M M M M M M M M M C X.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.@.A M M M M M M M         ",
"      M M M M M M M M M M M M W 1.R g d d d d d d d d d d d d d d f P 1.Q j M M M M M M M       ",
"      M M M M M M M M M M M M ( 1.6 O O O O O O O O O O O O O O O O # &.[ O w M M M M M M       ",
"    M M M M M M M M M M M M M ( 1.5 O O O O O O O O O O O O O O O O O %.[ O O 1 v M M M M M     ",
"    M M M M M M M M M M M M M ( 1.5 O O O O O O O O O O O O O O O O O %.[ O O O * l M M M M     ",
"    M M M M M M M M M M M M M ( 1.5 O d # O O O O O O O O O O O O O O %.[ O O O O # r M M M     ",
"  M M M M M M M M M M M M M M ( 1.5 O ! Y & O O O O O O O O O O O O O %.[ O O O O O O 0 M M M   ",
"  M M M M M M M M M M M M M M ( 1.5 O ! 1.) 3 O O O O O O O O O O O O %.[ O O O O O O O : v M   ",
"  M M M M M M M M M M M M M M ( 1.5 O ! 1.1.| 6 O O O O O O O O O O O %.[ O O O O O O O O * k   ",
"M M M M M M M M M M M M M M M V t # O ! 1.1.1.o.u O O O O O O O O O O %.[ O O O O O O O O O # 9 ",
"M M M M M M M M M M M {  . . . .[ [ [ #.1.1.1.1.+.a O O O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M -.1.1.1.1.1.1.1.1.1.1.1.1.1.-.h O O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M -.1.1.1.1.1.1.1.1.1.1.1.1.1.1.:.F O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M ;.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.K O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M -.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.K O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M -.1.1.1.1.1.1.1.1.1.1.1.1.1.1.:.F O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M ;.1.1.1.1.1.1.1.1.1.1.1.1.1.-.h O O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M M -.1.1.1.1.1.1.1.1.1.1.1.1.+.a O O O O O O O O O %.[ O O O O O O O O O O O ",
"M M M M M M M M M M v y t t t t t t t ` 1.1.1.o.u O O O O O O O O O O %.[ O O O O O O O O O O O ",
"  M M M M M M M M M M k * O O U %.3 O ! 1.1.} 6 O O O O O O O O O O O %.[ O O O O O O O O O O   ",
"  M M M M M M M M M M M v : O T 1.5 O ! 1.! 3 O O O O O O O O O O O O %.[ O O O O O O O O O O   ",
"  M M M M M M M M M M M M M 2 T 1.5 O ! Y & O O O O O O O O O O O O O %.[ O O O O O O O O O O   ",
"    M M M M M M M M M M M M M / 1.5 O d # O O O O O O O O O O O O O O %.[ O O O O O O O O O     ",
"    M M M M M M M M M M M M M ( 1.5 O O O O O O O O O O O O O O O O O %.[ O O O O O O O O O     ",
"    M M M M M M M M M M M M M ( 1.5 O O O O O O O O O O O O O O O O O %.[ O O O O O O O O O     ",
"      M M M M M M M M M M M M ( 1.6 O O O O O O O O O O O O O O O O # &.} O O O O O O O O       ",
"      M M M M M M M M M M M M W 1.R g s s d s s d s s d s s d s d f P 1.) O O O O O O O O       ",
"        M M M M M M M M M M M C ..1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.1.%.i O O O O O O O         ",
"          M M M M M M M M M M M z S H H H H H H H H H H H H H H H H F 6 O O O O O O O           ",
"            M M M M M M M M M M M z * O O O O O O O O O O O O O O O O O O O O O O O             ",
"              M M M M M M M M M M M v , O O O O O O O O O O O O O O O O O O O O O               ",
"                M M M M M M M M M M M M 0 O O O O O O O O O O O O O O O O O O O                 ",
"                  M M M M M M M M M M M M e # O O O O O O O O O O O O O O O O                   ",
"                    M M M M M M M M M M M M k * O O O O O O O O O O O O O O                     ",
"                      M M M M M M M M M M M M v : O O O O O O O O O O O O                       ",
"                          M M M M M M M M M M M M 1 O O O O O O O O O                           ",
"                                M M M M M M M M M M w O O O O O                                 ",
"                                      M M M M M M M M e #                                       "
]