table=[
"48 48 209 2 ",
"   c None",
".  c #265774",
"X  c #43687C",
"o  c #2C6C90",
"O  c #29729D",
"+  c #29729E",
"@  c #2B749E",
"#  c #317296",
"$  c #38779B",
"%  c #51788D",
"&  c #2081B8",
"*  c #2283BA",
"=  c #2284BB",
"-  c #2484BA",
";  c #2385BC",
":  c #2586BC",
">  c #2486BD",
",  c #2787BD",
"<  c #2487BE",
"1  c #2885BA",
"2  c #2986BB",
"3  c #2D87BB",
"4  c #2588BF",
"5  c #2988BE",
"6  c #2B89BE",
"7  c #2E8BBF",
"8  c #4180A4",
"9  c #4685A8",
"0  c #5492B5",
"q  c #6293AE",
"w  c #6494AF",
"e  c #6596B1",
"r  c #6B9BB7",
"t  c #699FBD",
"y  c #6FA2BE",
"u  c #2689C1",
"i  c #2789C2",
"p  c #278AC2",
"a  c #2B8AC0",
"s  c #288AC3",
"d  c #2D8CC1",
"f  c #298CC4",
"g  c #2B8DC4",
"h  c #308DC2",
"j  c #308EC3",
"k  c #2D90C8",
"l  c #2F92C8",
"z  c #3390C4",
"x  c #3391C6",
"c  c #3591C4",
"v  c #3693C7",
"b  c #3395CC",
"n  c #3397CE",
"m  c #3894C8",
"M  c #3A95C9",
"N  c #3B97CB",
"B  c #3598CF",
"V  c #3D98CC",
"C  c #3E99CC",
"Z  c #3F9ACD",
"A  c #3F9ACE",
"S  c #3599D1",
"D  c #369BD2",
"F  c #369CD3",
"G  c #389AD0",
"H  c #3A9CD1",
"J  c #3D9DD3",
"K  c #399DD4",
"L  c #389ED5",
"P  c #3A9FD6",
"I  c #3C9ED5",
"U  c #3FA1D6",
"Y  c #3BA1D9",
"T  c #3DA3DB",
"R  c #3EA3DA",
"E  c #3DA4DD",
"W  c #3FA7E0",
"Q  c #429CCE",
"!  c #499CCB",
"~  c #4B9DCB",
"^  c #409CD0",
"/  c #419DD0",
"(  c #449DD0",
")  c #469FD2",
"_  c #4FA1CF",
"`  c #45A0D2",
"'  c #47A0D2",
"]  c #45A3D7",
"[  c #49A2D3",
"{  c #49A2D4",
"}  c #4AA4D4",
"|  c #4CA5D4",
" . c #4CA4D5",
".. c #4EA5D5",
"X. c #4FA6D5",
"o. c #40A2D8",
"O. c #43A5DA",
"+. c #40A6DD",
"@. c #43A7DD",
"#. c #48A6D9",
"$. c #4DA7D9",
"%. c #43A8DF",
"&. c #46A9DE",
"*. c #49AADD",
"=. c #4DA9DD",
"-. c #4FA8DC",
";. c #4FABDF",
":. c #55A5D2",
">. c #50A7D7",
",. c #53A8D5",
"<. c #5BA9D5",
"1. c #5FACD7",
"2. c #51A9DA",
"3. c #50A9DB",
"4. c #54ABDC",
"5. c #52ACDD",
"6. c #53ADDF",
"7. c #55ADDD",
"8. c #55AEDF",
"9. c #59ACD8",
"0. c #5CAEDA",
"q. c #5EAFDA",
"w. c #58AEDE",
"e. c #5AB0DF",
"r. c #6BA3C1",
"t. c #75AAC8",
"y. c #63AFDA",
"u. c #65B2DE",
"i. c #63B4DF",
"p. c #6AB5DE",
"a. c #40A9E1",
"s. c #40AAE3",
"d. c #44AAE1",
"f. c #46ABE1",
"g. c #43ACE4",
"h. c #47ADE4",
"j. c #49ACE2",
"k. c #4BAFE5",
"l. c #50AEE1",
"z. c #50AFE2",
"x. c #53AFE2",
"c. c #4FB1E5",
"v. c #57B1E2",
"b. c #52B0E4",
"n. c #50B3E6",
"m. c #54B1E4",
"M. c #57B2E4",
"N. c #54B3E6",
"B. c #5BB2E1",
"V. c #5AB2E2",
"C. c #5CB1E0",
"Z. c #5DB3E1",
"A. c #5AB4E5",
"S. c #5BB5E7",
"D. c #5DB4E4",
"F. c #5DB6E5",
"G. c #5FB6E5",
"H. c #5DB6E7",
"J. c #55B5E8",
"K. c #57B5E8",
"L. c #59B7EA",
"P. c #5CB7E9",
"I. c #5FB8E8",
"U. c #5FB9EA",
"Y. c #5AB9EC",
"T. c #5CBAEC",
"R. c #5FBBED",
"E. c #5FBCED",
"W. c #60B4E1",
"Q. c #61B5E3",
"!. c #67B6E0",
"~. c #64B5E2",
"^. c #62B7E6",
"/. c #64B7E5",
"(. c #69B6E1",
"). c #61B8E7",
"_. c #66B8E4",
"`. c #66BAE7",
"'. c #6BB8E2",
"]. c #6AB9E5",
"[. c #6ABBE7",
"{. c #6CBAE5",
"}. c #62B9E9",
"|. c #63BBEA",
" X c #65BAE9",
".X c #67BBE9",
"XX c #66BDEB",
"oX c #61BCEC",
"OX c #63BDED",
"+X c #64BDEC",
"@X c #65BEED",
"#X c #66BEEC",
"$X c #68BCEA",
"%X c #69BDEB",
"&X c #6BBDEA",
"*X c #6ABEEB",
"=X c #6DBDE8",
"-X c #6EBEEA",
";X c #73BCE4",
":X c #70BFE9",
">X c #72BEE8",
",X c #72BFE8",
"<X c #75C2EB",
"1X c #76C2EB",
"2X c #78C1E8",
"3X c #79C2EA",
"4X c #79C4EB",
"5X c #78C4EC",
"6X c #7AC5ED",
"                                                                                                ",
"                                                                                                ",
"                                                2 O                                             ",
"                                              2 * - O                                           ",
"                                            6 ; = * * O                                         ",
"                                          d < < ; * * - O                                       ",
"                                        j p 4 < < ; = * - O                                     ",
"                                      z p p 4 4 < < ; = * - @                                   ",
"                                    z g a p p 4 4 < < ; * * - @                                 ",
"                                  N l g g a p p 4 4 < < ; = * 2 .                               ",
"                                / b b b l g a p p 4 < < < ; < o                                 ",
"                              / B b b b b b l p p p 4 < < 6 #                                   ",
"                            ` D D B b b b b b b g p p 4 a #                                     ",
"                          ` D D D D D B B B b b b g p j #                                       ",
"                        ` L F F D D G G G G G B B b z $                                         ",
"                      { L L L L L L L H H H H H G / 8                                           ",
"                    } Y L L L I I I I J J J J / ) 9                                             ",
"                  } Y Y Y Y Y U U U U U ] #.#.3.0                                               ",
"                 .R R Y R R o.o.o.] *.=.=.=.6.u.X                                               ",
"               .E E R R R R O.O.*.l.=.=.=.=.6.6.6.6.4.4.3.` ) Q Z Z N c z j 7 6 6 2 2 2 3       ",
"             .W E @.@.@.O.O.@.l.l.l.l.l.6.5.6.6.3.=.3.$.$.) Z Z N N c c d a 6 < < * * * 2       ",
"           .W W @.@.@.@.@.&.n.n.l.l.l.l.6.6.6.6.6.6.3.3.$. ./ Z Z N N c z d a 6 2 ; * * 2       ",
"        ,.s.W W %.%.@.%.&.n.m.m.m.m.m.v.x.6.6.6.6.6.4.4.3.3.) Q Z Z N N c z d 6 6 < - * 3       ",
"      ,.s.s.W W f.f.%.f.c.m.m.m.m.m.m.m.V.V.V.6.w.6.6.6.4.3.[ ) Q Z Z N N c j 7 a 6 < = 3       ",
"      ,.g.s.s.f.f.f.&.j.J.J.A.J.A.A.m.A.A.V.V.V.v.e.w.6.6.4. .` ) Q Z Z N N c j 7 a < < 7       ",
"        ,.h.g.f.f.f.j.n.J.J.J.A.A.A.G.G.G.G.Z.V.V.e.e.w.w.6. .` ) ) Q Z N N c z j a 6 < 7       ",
"          9.h.h.h.j.j.J.J.L.L.A.G.G.G.G.G.G.G.G.Z.Z.Z.e.w.w.>. .[ ) Q Z Z N N c j d a 6 j       ",
"            0.k.h.k.k.L.L.P.P.P.G.I.I.^.G.G.G.W.W.W.Z.Z.e.w.>. .[ ` ) Q Z N N c z j d a c       ",
"              0.k.k.c.Y.Y.P.P.I.I.).).).^.^./.W.W.W.W.Z.Z.e.>. . .[ ` ) Z Z N N c j j d c       ",
"                `.n.n.Y.Y.R.I.I.I.}.}.}.}./.`.2X2X2X2X2X2X;Xp.p.u.y.y.1.<.<.:.:._ _ ~ ~ ~       ",
"                  i.J.R.R.R.I.I.}.}.}..X`.`.`.=Xt.                                              ",
"                    !.R.R.R.R.oX}.}.}..X`..X`.`.:Xy                                             ",
"                      :XE.R.oXoX}.@XXX.X.X$X$X].].:Xy                                           ",
"                        1XoXoXoX@XXXXX$X$X$X$X=X=X].:Xr                                         ",
"                          1XoXoXXX@X$X$X$X$X=X=X=X=X].{.e                                       ",
"                            5XoX@X@X@X$X$X$X=X:X:X{.`.!.'.w                                     ",
"                              5X@X@X@X$X$X$X=X=X{.].`.!.W.(.q                                   ",
"                                5XXXXX$X$X$X].].].].`.!.W.Z.!.q                                 ",
"                                  5XXXXX.X.X.X`.`.`./.W.W.Z.e.(.%                               ",
"                                    5XXX.X.X`.`.`././.W.Z.Z.W.t                                 ",
"                                      4X.X.X`.`.^./.W.W.Z.!.t                                   ",
"                                        1X}.).^.).^.G.G.`.r.                                    ",
"                                          1X).G.G.G.G.`.r.                                      ",
"                                            1XG.G.G./.r.                                        ",
"                                              1XA.`.r.                                          ",
"                                                1Xr.                                            ",
"                                                                                                ",
"                                                                                                "
]