table=[
"48 48 125 2 ",
"   c None",
".  c #BD404F",
"X  c #BD4150",
"o  c #C14251",
"O  c #D04453",
"+  c #DB4756",
"@  c #D64858",
"#  c #DC4B5C",
"$  c #C15663",
"%  c #D25267",
"&  c #DF576E",
"*  c #D45B6F",
"=  c #DF586F",
"-  c #E0596F",
";  c #E15D76",
":  c #E15F78",
">  c #DE6472",
",  c #E1647C",
"<  c #E3687F",
"1  c #E26B82",
"2  c #E37087",
"3  c #E4748A",
"4  c #E47A8E",
"5  c #E47E92",
"6  c #DD8C9C",
"7  c #E68094",
"8  c #E88296",
"9  c #E48699",
"0  c #E88699",
"q  c #E48B9D",
"w  c #E98A9C",
"e  c #DA9DA5",
"r  c #E58FA0",
"t  c #EA8FA0",
"y  c #E594A4",
"u  c #EA91A2",
"i  c #E69BAA",
"p  c #EC9CAC",
"a  c #E3A4AF",
"s  c #EDA0AF",
"d  c #E6A5B2",
"f  c #EEA5B3",
"g  c #E6ADB3",
"h  c #EFAAB7",
"j  c #E7ADB9",
"k  c #EFACB9",
"l  c #F0ADBA",
"z  c #E7B1BC",
"x  c #E8B2BD",
"c  c #F0B2BE",
"v  c #E8B7C2",
"b  c #E8BAC4",
"n  c #E9BEC8",
"m  c #F2BBC6",
"M  c #D7C8CD",
"N  c #D9D3D7",
"B  c #DAD8DB",
"V  c #E9C4CC",
"C  c #F4C4CD",
"Z  c #E9CAD1",
"A  c #F4C7D0",
"S  c #F5CBD3",
"D  c #EAD0D7",
"F  c #EAD5DA",
"G  c #EBD9DE",
"H  c #F7D4DB",
"J  c #F8D7DD",
"K  c #F7D8DE",
"L  c #F8D9DF",
"P  c #E1DFE2",
"I  c #EBDFE2",
"U  c #EBDDE1",
"Y  c #F8DCE1",
"T  c #F9DFE4",
"R  c #E3E1E3",
"E  c #E3E2E4",
"W  c #E6E4E7",
"Q  c #E2E0E3",
"!  c #EBE0E4",
"~  c #EBE2E6",
"^  c #EBE4E7",
"/  c #ECE5E7",
"(  c #ECE4E7",
")  c #ECE5E8",
"_  c #ECE6E9",
"`  c #ECE7E9",
"'  c #E9E7E9",
"]  c #EBE9EB",
"[  c #ECE8EA",
"{  c #ECE8EB",
"}  c #ECE9EB",
"|  c #ECEAEC",
" . c #ECEBEC",
".. c #ECEBED",
"X. c #ECECED",
"o. c #ECECEE",
"O. c #ECEDEE",
"+. c #ECEBED",
"@. c #F9E1E5",
"#. c #FAE4E8",
"$. c #FAE4E9",
"%. c #FAE7EA",
"&. c #FBE9ED",
"*. c #FBEAED",
"=. c #FBECEF",
"-. c #FCEEF1",
";. c #FCEFF1",
":. c #FCEFF2",
">. c #FCF0F2",
",. c #FCF2F4",
"<. c #FDF3F4",
"1. c #FDF3F5",
"2. c #FDF4F6",
"3. c #FDF5F7",
"4. c #FDF7F7",
"5. c #FEF7F8",
"6. c #FEF7F9",
"7. c #FEF8F9",
"8. c #FEF8FA",
"9. c #FEF9FA",
"0. c #FEFAFA",
"q. c #FEFAFB",
"w. c #FEFBFC",
"e. c #FEFCFD",
"r. c white",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B                     ",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B B                   ",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B B B                 ",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B B B B               ",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B B B B B             ",
"              B R | | | | | | | | | | | | | | | | | | | | | | | | | | | ] B B B B B B           ",
"              B R | | | | | | | | | | | | | | | } / | | | | | | | | | | ] B B B B B B B         ",
"              B R | | | | | | | | | | | | | | G y 5 z } | | | | | | | | ] B B B B B B B B       ",
"              B R | | | | | | | | | | | | | | i , 2 1 F | | | | | | | | | W R R R R R R R R     ",
"              B R | | | | | | | | | | | | | } q 4 d , Z X.| | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | | a 1 y 1 F | | | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | X.V , , 4 I | | | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | | ^ 9 ; r } | | | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | | X.x ; i | | | | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | | | d ; 2 D X.| | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | | ~ 4 2 1 q ~ | | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | X.V , j x , d } | | | | | | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | | } r 1 F ) y , v X.X.X.X.| | | | | | | | | | | |     ",
"              B R | | | | | | | | | | | | X.Z 1 i | / Z 3 1 j v v V F } | | | | | | | | | |     ",
"              B R | | | | | | | | | | | X.| i , y y 5 1 , : ; , , , 1 d ) | | | | | | | | |     ",
"              B R | | | | | | | | | X.) Z i , : < 3 q i z v 7 ; 9 x 5 1 F | | | | | | | | |     ",
"              B R | | | | | | | | } V 9 , ; 1 j Z I } | X.X.G y , 2 1 5 ~ | | | | | | | | |     ",
"              B R | | | | | | | } j , 3 5 : d | X.| | | | | | ) n y y Z | | | | | | | | | |     ",
"              B R | | | | | | X.Z 1 q b 2 7 I | | | | | | | | | X.| | | | | | | | | | | | |     ",
"              N R | | | | | | X.V , r 4 2 Z X.| | | | | | | | | | | | | | | | | | | | | | |     ",
"      X X . $ M E | | | | | | | ~ q , 4 V | | | | | | | | | | | | | | | | | | | | | | | | |     ",
"    X X X . $ M E | | | | | | | | ~ Z I | | | | | | | | | | | | | | | | | | | | | | | | | |     ",
"    o X X . $ M E | | | | | | | | | X.| | | | | | | | | | | | | | | | | | | | | | | | | | |     ",
"    O o X . $ M E | | | | | | | | | | | | | | | | | | | | X.| | | | | | | | | | | | | | | |     ",
"    + @ % % * 6 y i i i i i i i i i i i i i i i i i i i i n } | | | | | | | | | | | | | | |     ",
"    + # ; , , ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; ; 1 F | | | | | | | | | | | | | | |     ",
"    + # ; : : ; ; ; ; ; : : ; ; ; ; ; : : ; ; ; ; ; : : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; 1 f l f 7 : : 7 s s u 1 ; ; 7 h h f 2 ; : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; t w.5.q.-.w , S r.q.w.H 2 ; C r.2.>.w ; : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; u q.s 0 =.A , H @.0 h q.c : C &.8 3 , : : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; u q.p 5 &.A , H J , , J Y , C <.k p 1 : : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; u r.<.2.<.u , H K , : A $.1 C r.2.$.4 ; : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; u w.S c 0 , , H K , 1 T H , C &.0 3 , : : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; u q.t ; ; : , H &.f A q.p ; C $.1 ; : : : : , Z X.| | | | | | | | | | | | | |     ",
"    + # ; : ; w -.0 ; : : , C q.5.-.c , ; m K < : : : : : , Z X.| | | | | | | | | | | | | |     ",
"    + + ; : : , 8 , : : : : 2 8 8 3 , : : 2 4 : : : : : : , Z X.| | | | | | | | | | | | | |     ",
"    + + # & - - & - - - - - = & & & - - - = & - - - - - - ; V X.| | | | | | | | | | | | | |     ",
"      + + + + + + + + + + + + + + + + + + + + + + + + + + > F | | | | | | | | | | | | | | |     ",
"              e a g g g g g g g g g g g g g g g g g g g g Z | | | | | | | | | | | | | | | |     ",
"              B E X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.X.| | | | | | | | | | | | | | | |     ",
"              B B ' | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | |     ",
"              B B B P R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R R     ",
"              B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B B       "
]