table=[
"48 48 218 2 ",
"   c None",
".  c #B46E51",
"X  c #BA6E5A",
"o  c #C97D4D",
"O  c #FEA236",
"+  c #FCA53B",
"@  c #FBA43C",
"#  c #F8A53E",
"$  c #FEAB3B",
"%  c #FEB03D",
"&  c #AE9A7F",
"*  c #DD9250",
"=  c #EB9A4A",
"-  c #E19856",
";  c #EA9A54",
":  c #EA9A55",
">  c #EA9C56",
",  c #F8B340",
"<  c #FDB140",
"1  c #FDB943",
"2  c #FEBA43",
"3  c #FEBF46",
"4  c #F0A15E",
"5  c #F9BB57",
"6  c #CB8065",
"7  c #D38566",
"8  c #C99066",
"9  c #C99167",
"0  c #D19369",
"q  c #D7966C",
"w  c #DE926F",
"e  c #DB996E",
"r  c #DE9A6F",
"t  c #C88776",
"y  c #C09579",
"u  c #DA9479",
"i  c #EB9861",
"p  c #F19F6A",
"a  c #E19B71",
"s  c #E29873",
"d  c #E49D71",
"f  c #E79E72",
"g  c #E59975",
"h  c #E99E73",
"j  c #EC9F73",
"k  c #E89A76",
"l  c #EB9B77",
"z  c #EC9F74",
"x  c #F09D78",
"c  c #EFA063",
"v  c #F1A260",
"b  c #F7A869",
"n  c #F7A96B",
"m  c #F2B76C",
"M  c #EEA074",
"N  c #F0A275",
"B  c #FBAE73",
"V  c #F4A478",
"C  c #F6A779",
"Z  c #F3A67E",
"A  c #F7A87E",
"S  c #F8AA7C",
"D  c #F9AD7D",
"F  c #FAAF7F",
"G  c #FCB078",
"H  c #FCB27B",
"J  c #FDB47E",
"K  c #FEC548",
"L  c #FECD4B",
"P  c #FED04D",
"I  c #FED14E",
"U  c #FED34E",
"Y  c #FCD850",
"T  c #FEDA51",
"R  c #FEDD53",
"E  c #FFE657",
"W  c #FEE958",
"Q  c #D47591",
"!  c #D67690",
"~  c #D57592",
"^  c #D57692",
"/  c #E16DC0",
"(  c #F877CE",
")  c #7F96C7",
"_  c #4CA8C1",
"`  c #4CA9C1",
"'  c #44A3F4",
"]  c #5CC1DA",
"[  c #61CBE5",
"{  c #6BCEE1",
"}  c #68D6EF",
"|  c #75D8E7",
" . c #66D9F6",
".. c #6BDEF7",
"X. c #6FE1FB",
"o. c #74E5FD",
"O. c #AF9B80",
"+. c #B19A82",
"@. c #B29C82",
"#. c #BB9D8D",
"$. c #B9A388",
"%. c #BAA38D",
"&. c #A1B4A4",
"*. c #B1BBA8",
"=. c #BDB6BE",
"-. c #D69081",
";. c #DE9E86",
":. c #CB9D9A",
">. c #DDA48B",
",. c #D3B08F",
"<. c #C4AB92",
"1. c #C6AD92",
"2. c #C9A09B",
"3. c #CBAE99",
"4. c #DDA398",
"5. c #D7AB9F",
"6. c #CFB49B",
"7. c #DDB797",
"8. c #D0BA96",
"9. c #D3B79F",
"0. c #D8BA9F",
"q. c #E4A38B",
"w. c #EDAE8D",
"e. c #FCB280",
"r. c #FDB581",
"t. c #FDB784",
"y. c #FEBA86",
"u. c #E3BE9E",
"i. c #D683AA",
"p. c #D6BAA1",
"a. c #DCBCA4",
"s. c #DDBEA5",
"d. c #E4B0A2",
"f. c #E0B5A3",
"g. c #E8BFA1",
"h. c #E3B2AB",
"j. c #E7B8AF",
"k. c #EABFAF",
"l. c #ECB4B4",
"z. c #A4C4BA",
"x. c #ACCABC",
"c. c #FBD281",
"v. c #EAC59B",
"b. c #F7CC97",
"n. c #FBD59B",
"m. c #F9D19E",
"M. c #EEC2A2",
"N. c #E2C0A8",
"B. c #E6C4AB",
"V. c #E9C7AB",
"C. c #E8C6AC",
"Z. c #EBC6AE",
"A. c #EDC8AE",
"S. c #F4C8AA",
"D. c #F1CDAA",
"F. c #F5D3AF",
"G. c #F0D8AD",
"H. c #F0D9AD",
"J. c #F7DCAD",
"K. c #EEC9B0",
"L. c #EEC2BB",
"P. c #EECDB9",
"I. c #F0CBB2",
"U. c #F2CFB4",
"Y. c #FACCB0",
"T. c #F0C6BB",
"R. c #F5CEBE",
"E. c #F5D4B7",
"W. c #FED1B5",
"Q. c #F8DDB5",
"!. c #F4D0B8",
"~. c #F6D3BC",
"^. c #F2D7BC",
"/. c #FFD4B9",
"(. c #F8D6BF",
"). c #FED7BC",
"_. c #F7DABC",
"`. c #F8DABD",
"'. c #F9D8BF",
"]. c #F8DEBC",
"[. c #FEE5A7",
"{. c #FBE1AF",
"}. c #FBE4B6",
"|. c #F9E2BE",
" X c #FDE8B9",
".X c #FDECB9",
"XX c #FEEFB9",
"oX c #FBE8BF",
"OX c #FDEBBD",
"+X c #FA8CCD",
"@X c #FAA4C8",
"#X c #ABCFC4",
"$X c #ADD2C8",
"%X c #93C6E1",
"&X c #81EBF5",
"*X c #83ECF5",
"=X c #CACFCB",
"-X c #FBC6CA",
";X c #F0D1C1",
":X c #FBD8C2",
">X c #FFDBC1",
",X c #F9DDC2",
"<X c #FFDFC5",
"1X c #FAE4C2",
"2X c #FCECC0",
"3X c #FEEEC0",
"4X c #FCECC3",
"5X c #FBE9C4",
"6X c #FCECC7",
"7X c #FFE4C9",
"8X c #FFEACB",
"9X c #FDEDCA",
"0X c #FFEFCC",
"qX c #FEF0C3",
"wX c #FEF4C4",
"eX c #FEF9C6",
"rX c #FEF2CB",
"tX c #FFF5CE",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                            E                 T W                 E                             ",
"                          P T                 P T                 P R                           ",
"                        , 3 3 L             2 3 K P             2 3 L T                         ",
"                        + $ % 2             $ % % 3             $ % % K                         ",
"                        @ O O $             O O O %             O O O <                         ",
"                          @ O @               + +               @ O @                           ",
"                          ] *X                { *X                | &X                          ",
"                          ] o...              [ o.              _ } o.                          ",
"                          ] X. .              [ o.              _ } X.                          ",
"                          ] X. .              [ o.              _ } X.                          ",
"                        %.z.#Xx.            *.z.$X*.            &.z.#X8.                        ",
"          1.6.0.u.v.v.b.b.b.b.b.b.b.b.b.m.m.m.m.m.m.m.m.m.m.n.n.n.n.n.n.n.n.n.n.n.n.n.          ",
"        $.<.6.0.s.N.V.D.D.D.D.D.D.D.F.F.F.F.E.Q.Q.Q.Q.Q.}.}.}. X XXXXXXXXXXXXXXXXXXX X{.        ",
"      @.$.<.6.p.s.h.l.Z.A.Z.A.A.K.I.U.U.E.E.!.=X_.].].|.oXoX2XqXwXwXeXeXeX[.XXeXwXwXOX}.G.      ",
"      O.$.<.6.p.s.i.( l.A.A.A.A.I.U.U.!.E.E.=.' %X_.].].|.|.oX2X2XqXqXwX[.3 c.wXwXqXOX}.G.      ",
"      & $.<.6.p.s.5./ +XA.Z.A.K.I.U.U.!.E.E.P.) ' =X_._._.].].|.|.oXoX2Xm 5  X2X2X2XOX}.G.      ",
"      & $.<.6.p.s.N.5.l.A.A.A.K.I.U.U.!.E.~.~.P.=.^._.'._.].].|.|.oXoXoXm.J.2X2X2X2XOX}.G.      ",
"      & $.<.6.p.s.N.B.Z.A.A.K.K.I.U.!.!.~.~.~.(.(.'.'.'.'.].].|.1XoXoX2X2X2X2X2X2X2XOX}.G.      ",
"      & $.<.6.p.s.N.B.Z.A.A.K.I.M.m U.!.~.~.~.(.(.(.'.'.'.~.@X:X1X1X5X2X2X2X2X2X2X2XOX}.G.      ",
"      & $.<.6.p.s.N.B.Z.A.K.K.g.- = D.!.~.(.(.(.'.(.'.'.'.L./ +X,X5X5X5X6X6X2X2X2X2XOX}.G.      ",
"      & $.<.6.p.s.N.B.Z.A.K.K.>.= M.!.~.~.(.(.'.'.'.'.'.,X,Xl./ -X5X9X9X9X6X2X2X2XoXOX}.G.      ",
"      & $.<.6.p.s.N.B.V.A.K.K.Z.Z.!.!.~.~.(.(.:X:X:X'.'.,X,X1X,X5X6X6X6X6X6X2X5XoXoX XQ.G.      ",
"      +.$.<.3.9.s.N.B.V.Z.K.K.I.U.!.!.!.~.(.:X:X:X:X:X'.,X,X1X5X6X9X9X9X6X6X5X5XoXoX}.J.G.      ",
"      #.#.<.3.5.5.f.N.B.Z.K.K.I.K.k.d.d.T.R.(.:X:X:X(.R.k.f.P.,X1X9X9X9X6X1X^.^.^.].Q.G.V.      ",
"      %.:.2.:.6 q r >.h.j.k.k.j.4.u s 6 t h.L.R.R.T.j.w.Z 7 X 4.L.;X;X;XP.M.q . t j.Z.k.Z.      ",
"        y t 6 0 e r s a ;.>.;.u s h z j w 7 -.4.4.q.Z F F F N 7 6 u q.w.r.H B c o o e 8.        ",
"          8 0 q e r r s f f f f h h z z M N N C A S F F F e.e.e.e.e.e.H H B B b 4 : *           ",
"          8 0 q e r r s s f f f f h z j M N N C C S F F e.e.r.r.r.e.J H H H B b 4 : *           ",
"          8 0 q e r r s s f f f f h z j M N N C C S F F e.r.r.t.r.r.J H H H B b 4 : *           ",
"          8 0 q e r s s f f f f h z z M M N C C S F F e.r.t.t.y.y.t.r.J H H B b v > *           ",
"          ,.7.7.g.M.S.Y.W.W././.).).>X>X>X<X<X<X7X7X7X8X8X8X0X9X0XrXtXtXtXrXqXOX X}.J.          ",
"          ,.7.7.g.M.S.Y.W.W././.).).>X>X>X<X<X<X7X7X7X8X8X8X0X9X0XrXtXtXtXrXqXOX X}.J.          ",
"          ,.7.7.u.M.S.Y.W.W.W././.).).>X>X>X<X<X7X7X7X7X8X8X8X9X0XrXrXtXrXqX2XOX X}.J.          ",
"          8 0 q e r r s s f f f h h z z M N C C S F F e.r.t.y.y.y.y.t.J H H B b v : *           ",
"          8 0 q e r r s s f f f f h z j z N N C S F F e.r.t.y.y.y.t.r.J H H B b v : *           ",
"          8 0 q e r r s s f f f h h z z M N N C S F F e.r.t.y.y.y.t.r.J H H B b v : *           ",
"          8 0 q e r r s s f f f f h z j M N N C C S F e.e.t.t.y.t.t.r.J H H B b v : *           ",
"          8 0 q e r r s s f f f f h z j M N N C C S F F e.r.t.t.t.r.e.J H H B b 4 : *           ",
"          8 0 q e r r s s f f f h h z z M N N C C S F F e.e.r.r.r.r.J H H H B b 4 : *           ",
"          8 0 q e r r s s f f f f h z j M N N C C S F F F e.e.r.r.e.H H H B B b 4 : *           ",
"          0 q w s s s g g g k k k k k k x x x x C Z Z A A A A A A A A A C C C p p i -           ",
"            Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q Q             ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "
]